package com.mysticai.astrology.dto;

import java.util.List;

/**
 * Dynamic per-category action payload generated by the Cosmic Action Engine.
 */
public record PlannerCategoryAction(
        PlannerCategory category,
        String categoryLabel,
        int score,
        List<String> dos,
        List<String> donts,
        String reasoning,
        List<String> supportingAspects,
        boolean mercuryRetrograde,
        String moonPhase,
        String source
) {}
