apiVersion: v1
kind: Secret
metadata:
  name: mystic-local-secret
  namespace: mystic-local
type: Opaque
stringData:
  DB_PASSWORD: "mystic123"
  RABBITMQ_PASSWORD: "mystic123"
  REDIS_PASSWORD: "mystic123"
  JWT_SECRET: "bXlzdGljLWxvY2FsLXN0YWdlLWp3dC1zZWNyZXQta2V5LTIwMjYtMDMtMTM="
  INTERNAL_GATEWAY_KEY: "mystic-local-stage-internal-key-2026"
  VERIFICATION_TOKEN_PEPPER: "mystic-local-stage-verification-pepper"
  PASSWORD_RESET_TOKEN_PEPPER: "mystic-local-stage-reset-pepper"
  ADMIN_JWT_SECRET: "mystic-local-admin-jwt-secret-2026-strong"

