import { DiscoverModule } from './types';

export const DISCOVER_MODULES: DiscoverModule[] = [
  // ── Cosmic Flow ──
  {
    id: 'daily-summary',
    titleKey: 'discover.dailySummary',
    descriptionKey: 'discover.dailySummaryDesc',
    icon: 'sunny',
    route: '/daily-summary',
    section: 'cosmicFlow',
    keywords: ['günlük', 'özet', 'daily', 'summary', 'transit', 'enerji', 'energy'],
    gradientDark: ['#4A1A8A', '#1A0A3A'],
    gradientLight: ['#A78BFA', '#7C3AED'],
    glowOnCriticalTransit: true,
  },
  {
    id: 'sky-pulse',
    titleKey: 'discover.skyPulse',
    descriptionKey: 'discover.skyPulseDesc',
    icon: 'planet',
    route: '/(tabs)/transit-detail',
    section: 'cosmicFlow',
    keywords: ['gökyüzü', 'gezegen', 'transit', 'sky', 'pulse', 'planet', 'ay', 'moon'],
    gradientDark: ['#0F3460', '#16213E'],
    gradientLight: ['#60A5FA', '#3B82F6'],
  },
  {
    id: 'weekly-swot',
    titleKey: 'discover.weeklySwot',
    descriptionKey: 'discover.weeklySwotDesc',
    icon: 'analytics',
    route: '/(tabs)/weekly-analysis',
    section: 'cosmicFlow',
    keywords: ['haftalık', 'swot', 'weekly', 'analiz', 'güç', 'fırsat', 'strength', 'opportunity'],
    gradientDark: ['#1A3A2A', '#0A1A0A'],
    gradientLight: ['#6EE7B7', '#34D399'],
  },

  {
    id: 'horoscope',
    titleKey: 'discover.horoscopeTitle',
    descriptionKey: 'discover.horoscopeDesc',
    icon: 'star',
    route: '/(tabs)/horoscope',
    section: 'cosmicFlow',
    keywords: ['burc\u0327', 'horoscope', 'gu\u0308nlu\u0308k', 'daily', 'haftal\u0131k', 'weekly', 'zodiac', 'astroloji'],
    gradientDark: ['#3A1A5A', '#1A0A2A'],
    gradientLight: ['#C084FC', '#A855F7'],
  },

  // ── Tools ──
  {
    id: 'decision-compass',
    titleKey: 'discover.decisionCompass',
    descriptionKey: 'discover.decisionCompassDesc',
    icon: 'compass',
    route: '/decision-compass',
    section: 'tools',
    keywords: ['karar', 'pusula', 'decision', 'compass', 'rehber', 'guide'],
    gradientDark: ['#4A2A0A', '#2A1A0A'],
    gradientLight: ['#FBBF24', '#F59E0B'],
  },
  {
    id: 'cosmic-planner',
    titleKey: 'discover.cosmicPlanner',
    descriptionKey: 'discover.cosmicPlannerDesc',
    icon: 'calendar',
    route: '/(tabs)/calendar',
    section: 'tools',
    keywords: ['takvim', 'planlayıcı', 'planner', 'calendar', 'şanslı', 'lucky'],
    gradientDark: ['#1A2A4A', '#0A1A2A'],
    gradientLight: ['#93C5FD', '#60A5FA'],
  },
  {
    id: 'dream-journal',
    titleKey: 'discover.dreamJournal',
    descriptionKey: 'discover.dreamJournalDesc',
    icon: 'moon',
    route: '/(tabs)/dreams',
    section: 'tools',
    keywords: ['rüya', 'dream', 'günlük', 'journal', 'bilinçaltı', 'sembol', 'symbol'],
    gradientDark: ['#2A1A4A', '#1A0A2A'],
    gradientLight: ['#C4B5FD', '#A78BFA'],
  },
  {
    id: 'star-mate',
    titleKey: 'discover.starMate',
    descriptionKey: 'discover.starMateDesc',
    icon: 'sparkles',
    route: '/(tabs)/star-mate',
    section: 'tools',
    keywords: ['yıldız', 'eş', 'star', 'mate', 'eşleşme', 'match'],
    gradientDark: ['#3A1A3A', '#1A0A1A'],
    gradientLight: ['#F9A8D4', '#F472B6'],
  },

  // ── Wisdom ──
  {
    id: 'numerology',
    titleKey: 'discover.numerology',
    descriptionKey: 'discover.numerologyDesc',
    icon: 'keypad',
    route: '/numerology',
    section: 'wisdom',
    keywords: ['numeroloji', 'numerology', 'sayı', 'number', 'yaşam yolu', 'life path'],
    gradientDark: ['#3A2A0A', '#1A1A0A'],
    gradientLight: ['#FDE68A', '#FCD34D'],
  },
  {
    id: 'name-analysis',
    titleKey: 'discover.nameAnalysis',
    descriptionKey: 'discover.nameAnalysisDesc',
    icon: 'text',
    route: '/(tabs)/name-analysis',
    section: 'wisdom',
    keywords: ['isim', 'analiz', 'name', 'analysis', 'titreşim', 'vibration'],
    gradientDark: ['#2A2A3A', '#1A1A2A'],
    gradientLight: ['#CBD5E1', '#94A3B8'],
  },
  {
    id: 'natal-chart',
    titleKey: 'discover.natalChart',
    descriptionKey: 'discover.natalChartDesc',
    icon: 'globe',
    route: '/night-sky-poster-preview',
    section: 'wisdom',
    keywords: ['natal', 'harita', 'doğum', 'chart', 'birth', 'gökyüzü', 'night sky'],
    gradientDark: ['#0A2A3A', '#0A1A2A'],
    gradientLight: ['#67E8F9', '#22D3EE'],
  },
  {
    id: 'spiritual',
    titleKey: 'discover.spiritual',
    descriptionKey: 'discover.spiritualDesc',
    icon: 'heart',
    route: '/spiritual',
    section: 'wisdom',
    keywords: ['dua', 'esma', 'prayer', 'spiritual', 'ruhani', 'zikir'],
    gradientDark: ['#1A3A1A', '#0A2A0A'],
    gradientLight: ['#86EFAC', '#4ADE80'],
  },
  {
    id: 'compatibility',
    titleKey: 'discover.compatibility',
    descriptionKey: 'discover.compatibilityDesc',
    icon: 'heart-circle',
    route: '/(tabs)/compatibility',
    section: 'wisdom',
    keywords: ['sinastri', 'synastry', 'uyum', 'compatibility', 'ilişki', 'relationship'],
    gradientDark: ['#3A0A2A', '#2A0A1A'],
    gradientLight: ['#FCA5A5', '#F87171'],
  },
];
