apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-web
  namespace: mystic-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-web
  template:
    metadata:
      labels:
        app: admin-web
    spec:
      containers:
        - name: admin-web
          image: __REPLACE_IMAGE_ADMIN_WEB__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mystic-stage-config
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: admin-web
  namespace: mystic-stage
spec:
  selector:
    app: admin-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
