apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mystic-stage-ingress
  namespace: mystic-stage
  annotations:
    cert-manager.io/cluster-issuer: "__REPLACE_CLUSTER_ISSUER__"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "__REPLACE_APP_HOST__"
        - "__REPLACE_ADMIN_HOST__"
      secretName: "__REPLACE_TLS_SECRET_NAME__"
  rules:
    - host: __REPLACE_APP_HOST__
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mobile-web
                port:
                  number: 80
    - host: __REPLACE_ADMIN_HOST__
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-web
                port:
                  number: 80
