apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: mystic-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: __REPLACE_IMAGE_SERVICE_REGISTRY__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: mystic-stage
spec:
  selector:
    app: service-registry
  ports:
    - name: http
      port: 8761
      targetPort: 8761
