import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Image,
  Linking,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import * as Haptics from 'expo-haptics';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import ViewShot from 'react-native-view-shot';
import { Ionicons } from '@expo/vector-icons';
import { SafeScreen } from '../../components/ui';
import { useTheme } from '../../context/ThemeContext';
import NatalChartProPanels from '../../components/Astrology/NatalChartProPanels';
import { useNatalVisualsStore } from '../../store/useNatalVisualsStore';
import { useGenerateMatchImage } from '../../hooks/useGenerateMatchImage';
import {
  ShareServiceError,
  saveToGallery,
  shareImage,
} from '../../services/share.service';

type CaptureAction = 'share' | 'save' | 'pdf' | null;
type VisualPresetKey = 'all' | 'wheel' | 'matrix' | 'balance';

type VisualPreset = {
  key: VisualPresetKey;
  label: string;
  sub: string;
  panels?: Array<'wheel' | 'matrix' | 'balance'>;
  captureWidth: number;
  captureHeight: number;
  canvasWidth: number;
};

const VISUAL_PRESETS: VisualPreset[] = [
  {
    key: 'all',
    label: 'Tam Set',
    sub: 'Natal + Matrix + Denge',
    panels: ['wheel', 'matrix', 'balance'],
    captureWidth: 1400,
    captureHeight: 2200,
    canvasWidth: 680,
  },
  {
    key: 'wheel',
    label: 'Natal Wheel',
    sub: 'SVG harita',
    panels: ['wheel'],
    captureWidth: 1200,
    captureHeight: 1500,
    canvasWidth: 520,
  },
  {
    key: 'matrix',
    label: 'Açı Matrisi',
    sub: 'Tam grid export',
    panels: ['matrix'],
    captureWidth: 1600,
    captureHeight: 1250,
    canvasWidth: 700,
  },
  {
    key: 'balance',
    label: 'Kozmik Denge',
    sub: 'Element / nitelik',
    panels: ['balance'],
    captureWidth: 1200,
    captureHeight: 1200,
    canvasWidth: 520,
  },
];

function buildVisualsPdfHtml(imageUri: string, title: string) {
  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <style>
        body { margin:0; padding:24px; background:#f6f8fc; font-family:-apple-system,BlinkMacSystemFont,Arial,sans-serif; }
        .wrap { max-width:980px; margin:0 auto; }
        h1 { margin:0 0 12px; font-size:18px; color:#0f172a; letter-spacing:0.2px; }
        img { width:100%; height:auto; display:block; border-radius:18px; box-shadow:0 12px 28px rgba(15,23,42,0.14); background:#fff; }
      </style>
    </head>
    <body>
      <div class="wrap">
        <h1>${title}</h1>
        <img src="${imageUri}" />
      </div>
    </body>
  </html>`;
}

export default function NatalVisualsPreviewScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const draft = useNatalVisualsStore((s) => s.draft);
  const clearDraft = useNatalVisualsStore((s) => s.clearDraft);

  const viewShotRef = useRef<ViewShot | null>(null);
  const [layoutTick, setLayoutTick] = useState(0);
  const [presetKey, setPresetKey] = useState<VisualPresetKey>('all');
  const [actionLoading, setActionLoading] = useState<CaptureAction>(null);
  const [successText, setSuccessText] = useState<string | null>(null);

  const preset = useMemo(
    () => VISUAL_PRESETS.find((item) => item.key === presetKey) ?? VISUAL_PRESETS[0],
    [presetKey],
  );

  const captureConfig = useMemo(
    () => ({
      width: preset.captureWidth,
      height: preset.captureHeight,
      cacheSubdir: 'natal-visuals-share',
      filePrefix: `natal-visuals-${preset.key}`,
    }),
    [preset.captureWidth, preset.captureHeight, preset.key],
  );

  const { imageUri, loading, error, generate, retry } = useGenerateMatchImage(viewShotRef, captureConfig);
  const autoGeneratedForKeyRef = useRef<string | null>(null);

  const draftKey = useMemo(
    () =>
      draft
        ? `${draft.name}|${draft.birthDate}|${draft.birthTime ?? 'unknown'}|${draft.createdAt}`
        : null,
    [draft],
  );

  const renderKey = useMemo(
    () => (draftKey ? `${draftKey}|${preset.key}` : null),
    [draftKey, preset.key],
  );

  useEffect(() => {
    return () => {
      clearDraft();
    };
  }, [clearDraft]);

  useEffect(() => {
    if (!draft || !layoutTick || !renderKey) return;
    if (autoGeneratedForKeyRef.current === renderKey) return;
    autoGeneratedForKeyRef.current = renderKey;
    void generate().catch(() => {
      // handled by hook
    });
  }, [draft, layoutTick, renderKey, generate]);

  useEffect(() => {
    if (!successText) return;
    const timer = setTimeout(() => setSuccessText(null), 1800);
    return () => clearTimeout(timer);
  }, [successText]);

  const notifySuccess = useCallback(async (message: string) => {
    setSuccessText(message);
    try {
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch {
      // no-op
    }
  }, []);

  const presentShareError = useCallback(async (title: string, cause: unknown) => {
    const error =
      cause instanceof ShareServiceError
        ? cause
        : new Error((cause as any)?.message ?? 'İşlem tamamlanamadı.');

    const openSettings = async () => {
      try {
        await Linking.openSettings();
      } catch {
        Alert.alert('Ayarlar Açılamadı', 'Lütfen Ayarlar uygulamasını manuel olarak açın.');
      }
    };

    if (error instanceof ShareServiceError && error.suggestOpenSettings) {
      Alert.alert(title, error.message, [
        { text: 'Vazgeç', style: 'cancel' },
        { text: 'Ayarları Aç', onPress: () => void openSettings() },
      ]);
      return;
    }

    Alert.alert(title, error.message);
  }, []);

  const runAction = useCallback(
    async (action: Exclude<CaptureAction, null>, title: string, fn: () => Promise<void>) => {
      if (!imageUri) return;
      setActionLoading(action);
      try {
        await fn();
      } catch (e) {
        await presentShareError(title, e);
      } finally {
        setActionLoading(null);
      }
    },
    [imageUri, presentShareError],
  );

  const handleRegenerate = useCallback(async () => {
    setSuccessText(null);
    autoGeneratedForKeyRef.current = null;
    try {
      await retry();
    } catch {
      await presentShareError('Görsel Oluşturulamadı', new Error('Natal görseller yeniden oluşturulamadı.'));
    }
  }, [retry, presentShareError]);

  const handleShare = useCallback(async () => {
    await runAction('share', 'Paylaşım Hatası', async () => {
      await shareImage(imageUri!);
      await notifySuccess('Paylaşım ekranı açıldı');
    });
  }, [runAction, imageUri, notifySuccess]);

  const handleSave = useCallback(async () => {
    await runAction('save', 'Kaydetme Hatası', async () => {
      const result = await saveToGallery(imageUri!);
      await notifySuccess(result.message ?? 'Görsel galeriye kaydedildi');
    });
  }, [runAction, imageUri, notifySuccess]);

  const handleExportPdf = useCallback(async () => {
    await runAction('pdf', 'PDF Hatası', async () => {
      const html = buildVisualsPdfHtml(imageUri!, `Kozmik Harita Görselleri • ${draft?.name ?? 'Profil'}`);
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Natal Görseller (PDF)',
        });
      }
      await notifySuccess('PDF hazırlandı');
    });
  }, [runAction, imageUri, draft?.name, notifySuccess]);

  if (!draft) {
    return (
      <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
        <View style={styles.emptyWrap}>
          <Ionicons name="scan-outline" size={28} color={colors.violet} />
          <Text style={[styles.emptyTitle, { color: colors.text }]}>Natal görsel verisi bulunamadı</Text>
          <Text style={[styles.emptySub, { color: colors.subtext }]}>
            Önce Haritam ekranındaki "Tam Ekran Gör • İndir" butonunu kullan.
          </Text>
          <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={() => router.back()}>
            <Text style={styles.primaryBtnText}>Geri Dön</Text>
          </Pressable>
        </View>
      </SafeScreen>
    );
  }

  return (
    <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
      <View pointerEvents="none" style={styles.captureHost}>
        <ViewShot
          ref={viewShotRef}
          style={[styles.captureCanvas, { width: preset.canvasWidth }]}
          onLayout={() => setLayoutTick(Date.now())}
          options={{
            format: 'png',
            quality: 1,
            result: 'tmpfile',
            width: preset.captureWidth,
            height: preset.captureHeight,
          } as any}
        >
          <View style={[styles.captureCard, { backgroundColor: colors.background, borderColor: colors.border }]}>
            <View style={styles.captureHeader}>
              <Text style={[styles.captureTitle, { color: colors.text }]}>
                {draft.name ?? 'Kozmik Harita'}
              </Text>
              <Text style={[styles.captureMeta, { color: colors.subtext }]}>
                {draft.birthDate} • {draft.birthTime?.slice(0, 5) ?? 'Saat bilinmiyor'} • {draft.birthLocation ?? 'Konum'}
              </Text>
            </View>
            <NatalChartProPanels
              planets={draft.planets}
              houses={draft.houses}
              aspects={draft.aspects}
              risingSign={draft.risingSign}
              panels={preset.panels}
            />
          </View>
        </ViewShot>
      </View>

      <View style={styles.header}>
        <Pressable
          style={[styles.iconBtn, { backgroundColor: colors.surface, borderColor: colors.border }]}
          onPress={() => router.back()}
        >
          <Ionicons name="arrow-back" size={18} color={colors.text} />
        </Pressable>
        <View style={styles.headerTextWrap}>
          <Text style={[styles.headerTitle, { color: colors.text }]}>Profesyonel Natal Görseller</Text>
          <Text style={[styles.headerSub, { color: colors.subtext }]}>
            Tam ekran önizle, PNG/PDF olarak indir veya paylaş.
          </Text>
        </View>
      </View>

      {successText ? (
        <View style={[styles.successBanner, { backgroundColor: colors.successBg, borderColor: colors.successLight }]}>
          <Ionicons name="checkmark-circle" size={16} color={colors.success} />
          <Text style={[styles.successText, { color: colors.success }]}>{successText}</Text>
        </View>
      ) : null}

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={[styles.presetCard, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>Görsel Preseti</Text>
          <Text style={[styles.sectionSub, { color: colors.subtext }]}>
            Açı matrisi preset’i export için geniş canvas kullanır; böylece grid tam görünür.
          </Text>
          <View style={styles.presetRow}>
            {VISUAL_PRESETS.map((item) => {
              const active = item.key === preset.key;
              return (
                <Pressable
                  key={item.key}
                  style={[
                    styles.presetChip,
                    { backgroundColor: colors.background, borderColor: colors.border },
                    active && { borderColor: colors.violet, backgroundColor: colors.surfaceAlt },
                  ]}
                  onPress={() => setPresetKey(item.key)}
                  disabled={loading || actionLoading != null}
                >
                  <Text style={[styles.presetChipLabel, { color: active ? colors.violet : colors.text }]}>
                    {item.label}
                  </Text>
                  <Text style={[styles.presetChipSub, { color: colors.subtext }]} numberOfLines={1}>
                    {item.sub}
                  </Text>
                </Pressable>
              );
            })}
          </View>
        </View>

        <View style={[styles.previewShell, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          {loading ? (
            <View style={styles.loaderWrap}>
              <View style={[styles.loaderGhost, { backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} />
              <ActivityIndicator size="large" color={colors.violet} />
              <Text style={[styles.loaderTitle, { color: colors.text }]}>Görsel hazırlanıyor…</Text>
              <Text style={[styles.loaderSub, { color: colors.subtext }]}>
                {preset.label} preset’i için yüksek çözünürlük export hazırlanıyor.
              </Text>
            </View>
          ) : imageUri ? (
            <>
              <View style={[styles.previewImageWrap, { backgroundColor: colors.background, borderColor: colors.border }]}>
                <Image source={{ uri: imageUri }} style={styles.previewImage} resizeMode="contain" />
              </View>
              <Text style={[styles.previewMeta, { color: colors.subtext }]}>
                {preset.label} • {draft.name ?? 'Profil'} • {draft.birthDate}
              </Text>
              <Text style={[styles.previewMeta, { color: colors.subtext }]}>
                PNG export: {preset.captureWidth}×{preset.captureHeight}
              </Text>
            </>
          ) : (
            <View style={styles.loaderWrap}>
              <Ionicons name="warning-outline" size={24} color={colors.warning} />
              <Text style={[styles.loaderTitle, { color: colors.text }]}>Görsel oluşturulamadı</Text>
              <Text style={[styles.loaderSub, { color: colors.subtext }]}>{error ?? 'Beklenmeyen hata.'}</Text>
              <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={handleRegenerate}>
                <Text style={styles.primaryBtnText}>Tekrar Dene</Text>
              </Pressable>
            </View>
          )}
        </View>

        <View style={styles.actionsBlock}>
          <Pressable
            style={[styles.secondaryWideBtn, { backgroundColor: colors.surface, borderColor: colors.border }]}
            onPress={handleRegenerate}
            disabled={loading || actionLoading != null}
          >
            <Ionicons name="refresh" size={16} color={colors.text} />
            <Text style={[styles.secondaryWideBtnText, { color: colors.text }]}>Yeniden Oluştur</Text>
          </Pressable>

          {imageUri && !loading ? (
            <>
              <Pressable
                style={[styles.primaryBtn, { backgroundColor: colors.violet }, actionLoading && styles.btnDisabled]}
                onPress={handleShare}
                disabled={actionLoading != null}
              >
                {actionLoading === 'share' ? (
                  <ActivityIndicator size="small" color="#FFF" />
                ) : (
                  <Ionicons name="share-social" size={16} color="#FFF" />
                )}
                <Text style={styles.primaryBtnText}>Paylaş</Text>
              </Pressable>

              <View style={styles.secondaryRow}>
                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleSave}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'save' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="download-outline" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>Galeriye Kaydet</Text>
                </Pressable>

                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleExportPdf}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'pdf' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="document-text-outline" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>PDF</Text>
                </Pressable>
              </View>
            </>
          ) : null}
        </View>
      </ScrollView>
    </SafeScreen>
  );
}

const styles = StyleSheet.create({
  captureHost: {
    position: 'absolute',
    left: -9999,
    top: -9999,
    opacity: 0,
  },
  captureCanvas: {
    width: 680,
  },
  captureCard: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    gap: 14,
  },
  captureHeader: {
    gap: 4,
  },
  captureTitle: {
    fontSize: 18,
    fontWeight: '800',
  },
  captureMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800' },
  headerSub: { fontSize: 12, lineHeight: 17 },
  successBanner: {
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  successText: { fontSize: 12, fontWeight: '600' },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 14,
  },
  presetCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  sectionSub: {
    fontSize: 12,
    lineHeight: 17,
  },
  presetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  presetChip: {
    minWidth: '47%' as any,
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 2,
  },
  presetChipLabel: {
    fontSize: 12.5,
    fontWeight: '700',
  },
  presetChipSub: {
    fontSize: 11,
  },
  previewShell: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  previewImageWrap: {
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
    minHeight: 320,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    width: '100%',
    height: 360,
  },
  previewMeta: {
    fontSize: 11.5,
    lineHeight: 16,
    textAlign: 'center',
  },
  loaderWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 320,
    gap: 8,
    paddingHorizontal: 16,
  },
  loaderGhost: {
    width: '100%',
    height: 180,
    borderRadius: 14,
    borderWidth: 1,
  },
  loaderTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  loaderSub: {
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 17,
  },
  actionsBlock: {
    gap: 10,
  },
  primaryBtn: {
    minHeight: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryBtnText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 13,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
  },
  secondaryBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
  },
  secondaryWideBtn: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
  },
  secondaryWideBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
  },
  btnDisabled: {
    opacity: 0.65,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptySub: {
    fontSize: 12.5,
    lineHeight: 18,
    textAlign: 'center',
  },
});
