import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Image,
  Linking,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import * as Haptics from 'expo-haptics';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import ViewShot from 'react-native-view-shot';
import { Ionicons } from '@expo/vector-icons';
import { SafeScreen } from '../../components/ui';
import { useTheme } from '../../context/ThemeContext';
import BirthNightSkyPoster from '../../components/Astrology/BirthNightSkyPoster';
import { useNightSkyPosterStore } from '../../store/useNightSkyPosterStore';
import { useGenerateMatchImage } from '../../hooks/useGenerateMatchImage';
import {
  createNightSkyPosterShareLink,
  fetchNightSkyProjection,
  type NightSkyPosterVariant,
  type NightSkyProjectionResponse,
} from '../../services/astrology.service';
import {
  ShareServiceError,
  instagramStory,
  saveToGallery,
  shareImage,
} from '../../services/share.service';

type ShareAction = 'share' | 'instagram' | 'save' | 'pdf' | null;
type VariantOption = { key: NightSkyPosterVariant; label: string; sub: string };

const META_INSTAGRAM_STORY_APP_ID =
  process.env.EXPO_PUBLIC_FACEBOOK_APP_ID || process.env.EXPO_PUBLIC_META_APP_ID || undefined;

const POSTER_VARIANTS: VariantOption[] = [
  { key: 'minimal', label: 'Minimal', sub: 'Temiz / sakin' },
  { key: 'constellation_heavy', label: 'Constellation', sub: 'Çizgiler yoğun' },
  { key: 'gold_edition', label: 'Gold Edition', sub: 'Altın vurgu' },
];

function buildPosterPdfHtml(imageUri: string, name: string) {
  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <style>
        body { margin:0; padding:0; background:#0a0d14; font-family: -apple-system, BlinkMacSystemFont, Arial, sans-serif; }
        .page { width:100%; min-height:100vh; display:flex; align-items:center; justify-content:center; padding:18px; box-sizing:border-box; }
        .wrap { width:100%; max-width:720px; }
        .title { color:#f8fafc; text-align:center; font-size:18px; margin:0 0 12px; letter-spacing:0.3px; }
        img { width:100%; height:auto; border-radius:16px; display:block; box-shadow: 0 10px 36px rgba(0,0,0,.35); }
      </style>
    </head>
    <body>
      <div class="page">
        <div class="wrap">
          <p class="title">The Night You Were Born • ${name}</p>
          <img src="${imageUri}" />
        </div>
      </div>
    </body>
  </html>`;
}

export default function NightSkyPosterPreviewScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const draft = useNightSkyPosterStore((s) => s.draft);
  const clearDraft = useNightSkyPosterStore((s) => s.clearDraft);

  const viewShotRef = useRef<ViewShot | null>(null);
  const [layoutTick, setLayoutTick] = useState(0);
  const [actionLoading, setActionLoading] = useState<ShareAction>(null);
  const [successText, setSuccessText] = useState<string | null>(null);
  const [variant, setVariant] = useState<NightSkyPosterVariant>('minimal');
  const [projection, setProjection] = useState<NightSkyProjectionResponse | null>(null);
  const [projectionLoading, setProjectionLoading] = useState(false);
  const [projectionError, setProjectionError] = useState<string | null>(null);
  const [resolvedShareUrl, setResolvedShareUrl] = useState<string | null>(null);
  const [shareLinkLoading, setShareLinkLoading] = useState(false);
  const [shareLinkError, setShareLinkError] = useState<string | null>(null);

  const captureConfig = useMemo(
    () => ({
      width: 1080,
      height: 1920,
      cacheSubdir: 'night-sky-share',
      filePrefix: 'night-sky-poster',
    }),
    [],
  );

  const { imageUri, loading, error, generate, retry } = useGenerateMatchImage(viewShotRef, captureConfig);
  const autoGeneratedForKeyRef = useRef<string | null>(null);
  const backendLoadSeqRef = useRef(0);

  const draftKey = useMemo(
    () => (draft ? `${draft.name}|${draft.birthDate}|${draft.birthTime ?? 'unknown'}|${draft.createdAt}` : null),
    [draft],
  );

  const renderKey = useMemo(
    () =>
      draftKey
        ? `${draftKey}|${variant}|${projection?.generatedAtUtc ?? 'no-proj'}|${resolvedShareUrl ?? draft?.shareUrl ?? 'no-share'}`
        : null,
    [draftKey, variant, projection?.generatedAtUtc, resolvedShareUrl, draft?.shareUrl],
  );

  useEffect(() => {
    autoGeneratedForKeyRef.current = null;
    setSuccessText(null);
    setVariant('minimal');
    setProjection(null);
    setProjectionError(null);
    setProjectionLoading(false);
    setResolvedShareUrl(draft?.shareUrl ?? null);
    setShareLinkError(null);
    setShareLinkLoading(false);
  }, [draftKey]);

  const loadBackendPosterData = useCallback(
    async (selectedVariant: NightSkyPosterVariant) => {
      if (!draft) return;
      const seq = ++backendLoadSeqRef.current;
      setProjectionLoading(true);
      setProjectionError(null);
      setShareLinkLoading(true);
      setShareLinkError(null);

      const projectionPromise = fetchNightSkyProjection({
        userId: draft.userId,
        chartId: draft.chartId,
        name: draft.name,
        birthDate: draft.birthDate,
        birthTime: draft.birthTime,
        birthLocation: draft.birthLocation,
        latitude: draft.latitude,
        longitude: draft.longitude,
        timezone: draft.timezone,
      });

      const shareLinkPromise = createNightSkyPosterShareLink({
        userId: draft.userId,
        chartId: draft.chartId,
        name: draft.name,
        birthDate: draft.birthDate,
        birthTime: draft.birthTime,
        birthLocation: draft.birthLocation,
        latitude: draft.latitude,
        longitude: draft.longitude,
        timezone: draft.timezone,
        variant: selectedVariant,
      });

      const [projectionRes, shareLinkRes] = await Promise.allSettled([projectionPromise, shareLinkPromise]);
      if (backendLoadSeqRef.current !== seq) return;

      if (projectionRes.status === 'fulfilled') {
        setProjection(projectionRes.value.data);
        setProjectionError(null);
      } else {
        setProjection(null);
        setProjectionError(
          (projectionRes.reason as any)?.response?.data?.message ??
            (projectionRes.reason as any)?.message ??
            'Gerçek gökyüzü projeksiyonu alınamadı. Lokal kompozisyon gösteriliyor.',
        );
      }
      setProjectionLoading(false);

      if (shareLinkRes.status === 'fulfilled') {
        setResolvedShareUrl(shareLinkRes.value.data.shareUrl || draft.shareUrl);
        setShareLinkError(null);
      } else {
        setResolvedShareUrl(draft.shareUrl);
        setShareLinkError(
          (shareLinkRes.reason as any)?.response?.data?.message ??
            (shareLinkRes.reason as any)?.message ??
            'Paylaşım linki üretilemedi. Varsayılan link kullanılıyor.',
        );
      }
      setShareLinkLoading(false);
    },
    [draft],
  );

  useEffect(() => {
    return () => {
      clearDraft();
    };
  }, [clearDraft]);

  useEffect(() => {
    if (!draft) return;
    void loadBackendPosterData(variant);
  }, [draft, variant, loadBackendPosterData]);

  useEffect(() => {
    if (!draft || !layoutTick) return;
    if (autoGeneratedForKeyRef.current === renderKey) return;
    autoGeneratedForKeyRef.current = renderKey;
    void generate().catch(() => {
      // handled by hook state
    });
  }, [draft, layoutTick, renderKey, generate]);

  useEffect(() => {
    if (!successText) return;
    const timer = setTimeout(() => setSuccessText(null), 1800);
    return () => clearTimeout(timer);
  }, [successText]);

  const notifySuccess = async (message: string) => {
    setSuccessText(message);
    try {
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch {
      // no-op
    }
  };

  const presentShareError = useCallback(async (title: string, cause: unknown) => {
    const error =
      cause instanceof ShareServiceError
        ? cause
        : new Error((cause as any)?.message ?? 'İşlem tamamlanamadı.');

    const openSettings = async () => {
      try {
        await Linking.openSettings();
      } catch {
        Alert.alert('Ayarlar Açılamadı', 'Lütfen Ayarlar uygulamasını manuel olarak açın.');
      }
    };

    if (error instanceof ShareServiceError && error.suggestOpenSettings) {
      Alert.alert(title, error.message, [
        { text: 'Vazgeç', style: 'cancel' },
        { text: 'Ayarları Aç', onPress: () => void openSettings() },
      ]);
      return;
    }

    Alert.alert(title, error.message);
  }, []);

  const runShareAction = async (
    action: Exclude<ShareAction, null>,
    errorTitle: string,
    fn: () => Promise<void>,
  ) => {
    if (!imageUri) return;
    setActionLoading(action);
    try {
      await fn();
    } catch (e) {
      await presentShareError(errorTitle, e);
    } finally {
      setActionLoading(null);
    }
  };

  const handleShare = async () => {
    await runShareAction('share', 'Paylaşım Hatası', async () => {
      await shareImage(imageUri!);
      await notifySuccess('Paylaşım ekranı açıldı');
    });
  };

  const handleInstagram = async () => {
    await runShareAction('instagram', 'Instagram Story Hatası', async () => {
      const result = await instagramStory(imageUri!, {
        attributionURL: resolvedShareUrl ?? draft?.shareUrl,
        appId: META_INSTAGRAM_STORY_APP_ID,
        fallbackToSystemShare: true,
      });
      await notifySuccess(result.fallbackUsed ? 'Sistem paylaşımı açıldı' : 'Instagram Story başlatıldı');
    });
  };

  const handleSave = async () => {
    await runShareAction('save', 'Kaydetme Hatası', async () => {
      const result = await saveToGallery(imageUri!);
      await notifySuccess(result.message ?? 'Poster galeriye kaydedildi');
    });
  };

  const handleExportPdf = async () => {
    await runShareAction('pdf', 'PDF Hatası', async () => {
      const html = buildPosterPdfHtml(imageUri!, draft?.name ?? 'Poster');
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Doğduğun Gece Posteri (PDF)',
        });
      }
      await notifySuccess('PDF hazırlandı');
    });
  };

  const handleRegenerate = async () => {
    setSuccessText(null);
    try {
      if (draft) {
        await loadBackendPosterData(variant);
      }
      await retry();
    } catch {
      await presentShareError('Poster Oluşturulamadı', new Error('Poster yeniden oluşturulamadı.'));
    }
  };

  if (!draft) {
    return (
      <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
        <View style={styles.emptyWrap}>
          <Ionicons name="moon-outline" size={28} color={colors.violet} />
          <Text style={[styles.emptyTitle, { color: colors.text }]}>Poster verisi bulunamadı</Text>
          <Text style={[styles.emptySub, { color: colors.subtext }]}>
            Önce harita ekranından "Doğduğun Gece Posteri" butonuna dokun.
          </Text>
          <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={() => router.back()}>
            <Text style={styles.primaryBtnText}>Geri Dön</Text>
          </Pressable>
        </View>
      </SafeScreen>
    );
  }

  return (
    <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
      <View pointerEvents="none" style={styles.captureHost}>
        <ViewShot
          ref={viewShotRef}
          style={styles.captureCanvas}
          onLayout={() => setLayoutTick(Date.now())}
          options={{
            format: 'png',
            quality: 1,
            result: 'tmpfile',
            width: 1080,
            height: 1920,
          } as any}
        >
          <BirthNightSkyPoster
            name={draft.name}
            birthDate={draft.birthDate}
            birthTime={draft.birthTime}
            birthLocation={draft.birthLocation}
            latitude={draft.latitude}
            longitude={draft.longitude}
            shareUrl={resolvedShareUrl ?? draft.shareUrl}
            planets={draft.planets}
            houses={draft.houses}
            variant={variant}
            projection={projection}
          />
        </ViewShot>
      </View>

      <View style={styles.header}>
        <Pressable
          style={[styles.iconBtn, { backgroundColor: colors.surface, borderColor: colors.border }]}
          onPress={() => router.back()}
        >
          <Ionicons name="arrow-back" size={18} color={colors.text} />
        </Pressable>
        <View style={styles.headerTextWrap}>
          <Text style={[styles.headerTitle, { color: colors.text }]}>Doğduğun Gece Posteri</Text>
          <Text style={[styles.headerSub, { color: colors.subtext }]}>
            Yüksek çözünürlük PNG/PDF üret, sonra paylaş.
          </Text>
        </View>
      </View>

      {successText ? (
        <View style={[styles.successBanner, { backgroundColor: colors.successBg, borderColor: colors.successLight }]}>
          <Ionicons name="checkmark-circle" size={16} color={colors.success} />
          <Text style={[styles.successText, { color: colors.success }]}>{successText}</Text>
        </View>
      ) : null}

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={[styles.variantCard, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          <View style={styles.variantHeader}>
            <View>
              <Text style={[styles.variantTitle, { color: colors.text }]}>Poster Varyantı</Text>
              <Text style={[styles.variantSub, { color: colors.subtext }]}>
                Stil değişince share token ve poster yeniden üretilir.
              </Text>
            </View>
            {(projectionLoading || shareLinkLoading) ? (
              <View style={styles.variantSyncWrap}>
                <ActivityIndicator size="small" color={colors.violet} />
                <Text style={[styles.variantSyncText, { color: colors.subtext }]}>Senkronize ediliyor…</Text>
              </View>
            ) : null}
          </View>

          <View style={styles.variantRow}>
            {POSTER_VARIANTS.map((opt) => {
              const active = variant === opt.key;
              return (
                <Pressable
                  key={opt.key}
                  style={[
                    styles.variantChip,
                    { backgroundColor: colors.background, borderColor: colors.border },
                    active && { borderColor: colors.violet, backgroundColor: colors.surfaceAlt },
                  ]}
                  onPress={() => setVariant(opt.key)}
                  disabled={loading || actionLoading != null}
                >
                  <Text style={[styles.variantChipLabel, { color: active ? colors.violet : colors.text }]}>{opt.label}</Text>
                  <Text style={[styles.variantChipSub, { color: colors.subtext }]} numberOfLines={1}>
                    {opt.sub}
                  </Text>
                </Pressable>
              );
            })}
          </View>

          {projection ? (
            <View style={[styles.backendBadge, { backgroundColor: colors.successBg, borderColor: colors.successLight }]}>
              <Ionicons name="planet-outline" size={14} color={colors.success} />
              <Text style={[styles.backendBadgeText, { color: colors.success }]}>
                Gerçek zenith projection aktif • {projection.projectionModel}
              </Text>
            </View>
          ) : null}

          {projectionError ? (
            <View style={[styles.backendBadge, { backgroundColor: colors.warningBg ?? colors.surfaceAlt, borderColor: colors.border }]}>
              <Ionicons name="warning-outline" size={14} color={colors.warning} />
              <Text style={[styles.backendBadgeText, { color: colors.warning }]}>{projectionError}</Text>
            </View>
          ) : null}

          {shareLinkError ? (
            <View style={[styles.backendBadge, { backgroundColor: colors.warningBg ?? colors.surfaceAlt, borderColor: colors.border }]}>
              <Ionicons name="link-outline" size={14} color={colors.warning} />
              <Text style={[styles.backendBadgeText, { color: colors.warning }]}>{shareLinkError}</Text>
            </View>
          ) : null}
        </View>

        <View style={[styles.previewShell, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          {loading ? (
            <View style={styles.loaderWrap}>
              <View style={[styles.loaderGhost, { backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} />
              <ActivityIndicator size="large" color={colors.violet} />
              <Text style={[styles.loaderTitle, { color: colors.text }]}>Poster oluşturuluyor…</Text>
              <Text style={[styles.loaderSub, { color: colors.subtext }]}>
                9:16 yüksek çözünürlüklü görsel hazırlanıyor.
              </Text>
            </View>
          ) : imageUri ? (
            <>
              <Image source={{ uri: imageUri }} style={styles.previewImage} resizeMode="contain" />
              <Text style={[styles.previewMeta, { color: colors.subtext }]}>
                {draft.birthDate} • {draft.birthTime?.slice(0, 5) ?? 'Saat bilinmiyor'} •{' '}
                {POSTER_VARIANTS.find((v) => v.key === variant)?.label ?? 'Minimal'}
              </Text>
              <Text style={[styles.previewMeta, { color: colors.subtext }]}>
                {projection ? `${projection.timezoneUsed} • Swiss Ephemeris horizontal coords` : 'Lokal fallback kompozisyon'}
              </Text>
            </>
          ) : (
            <View style={styles.loaderWrap}>
              <Ionicons name="warning-outline" size={24} color={colors.warning} />
              <Text style={[styles.loaderTitle, { color: colors.text }]}>Poster oluşturulamadı</Text>
              <Text style={[styles.loaderSub, { color: colors.subtext }]}>{error ?? 'Beklenmeyen hata.'}</Text>
              <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={handleRegenerate}>
                <Text style={styles.primaryBtnText}>Tekrar Dene</Text>
              </Pressable>
            </View>
          )}
        </View>

        <View style={styles.actionsBlock}>
          <Pressable
            style={[styles.secondaryWideBtn, { backgroundColor: colors.surface, borderColor: colors.border }]}
            onPress={handleRegenerate}
            disabled={loading || actionLoading != null}
          >
            <Ionicons name="refresh" size={16} color={colors.text} />
            <Text style={[styles.secondaryWideBtnText, { color: colors.text }]}>Posteri Yeniden Oluştur</Text>
          </Pressable>

          {imageUri && !loading ? (
            <>
              <Pressable
                style={[styles.primaryBtn, { backgroundColor: colors.violet }, actionLoading && styles.btnDisabled]}
                onPress={handleShare}
                disabled={actionLoading != null}
              >
                {actionLoading === 'share' ? (
                  <ActivityIndicator size="small" color="#FFF" />
                ) : (
                  <Ionicons name="share-social" size={16} color="#FFF" />
                )}
                <Text style={styles.primaryBtnText}>Paylaş</Text>
              </Pressable>

              <View style={styles.secondaryRow}>
                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleInstagram}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'instagram' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="logo-instagram" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>Instagram Story</Text>
                </Pressable>

                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleSave}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'save' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="download-outline" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>Galeri</Text>
                </Pressable>
              </View>

              <Pressable
                style={[styles.secondaryWideBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                onPress={handleExportPdf}
                disabled={actionLoading != null}
              >
                {actionLoading === 'pdf' ? (
                  <ActivityIndicator size="small" color={colors.text} />
                ) : (
                  <Ionicons name="document-text-outline" size={16} color={colors.text} />
                )}
                <Text style={[styles.secondaryWideBtnText, { color: colors.text }]}>PDF Olarak Paylaş</Text>
              </Pressable>
            </>
          ) : null}
        </View>
      </ScrollView>
    </SafeScreen>
  );
}

const styles = StyleSheet.create({
  captureHost: {
    position: 'absolute',
    opacity: 0,
    left: -9999,
    top: -9999,
  },
  captureCanvas: {
    width: 360,
    height: 640,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800' },
  headerSub: { fontSize: 12, lineHeight: 17 },
  successBanner: {
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  successText: { fontSize: 12, fontWeight: '600' },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 14,
  },
  variantCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  variantHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  variantTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  variantSub: {
    marginTop: 2,
    fontSize: 11.5,
    lineHeight: 16,
  },
  variantSyncWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 2,
  },
  variantSyncText: {
    fontSize: 11,
    fontWeight: '600',
  },
  variantRow: {
    flexDirection: 'row',
    gap: 8,
  },
  variantChip: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 56,
  },
  variantChipLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  variantChipSub: {
    marginTop: 2,
    fontSize: 10.5,
  },
  backendBadge: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  backendBadgeText: {
    flex: 1,
    fontSize: 11.5,
    lineHeight: 15,
    fontWeight: '600',
  },
  previewShell: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 320,
  },
  previewImage: {
    width: '100%',
    aspectRatio: 9 / 16,
    borderRadius: 14,
    backgroundColor: '#000',
  },
  previewMeta: {
    marginTop: 8,
    fontSize: 11.5,
  },
  loaderWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 24,
  },
  loaderGhost: {
    width: '100%',
    aspectRatio: 9 / 16,
    borderRadius: 14,
    borderWidth: 1,
  },
  loaderTitle: { fontSize: 14, fontWeight: '700' },
  loaderSub: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: 280,
  },
  actionsBlock: { gap: 10 },
  primaryBtn: {
    minHeight: 46,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryBtnText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 13,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  secondaryBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryWideBtn: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryWideBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
  },
  btnDisabled: {
    opacity: 0.65,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 10,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', textAlign: 'center' },
  emptySub: { fontSize: 13, lineHeight: 19, textAlign: 'center' },
});
