-- Expand spiritual content catalog with usable sample records.
-- Notes:
-- 1) Source notes remain explicit for editorial verification.
-- 2) Content is guidance-oriented and not a religious ruling.

INSERT INTO prayers (
    slug, title, category, source_label, source_note, arabic_text, transliteration_tr, meaning_tr,
    recommended_repeat_count, estimated_read_seconds, is_favoritable, disclaimer_text, difficulty_level, active
) VALUES
    ('sabah-huzur-kisa-01','Sabah Huzur Duasi (Kisa)','SABAH_AKSAM','GELENEKSEL',
     'Kaynak notu: Kisa sabah duasi/niyeti. Yayin oncesi editoryal dogrulama onerilir.',
     NULL,
     'Allahim, bugune huzur, denge ve hayirli niyetlerle baslamayi nasip eyle.',
     'Sabaha huzur ve hayir niyetiyle baslamaya yonelik kisa dua metni.',
     33,25,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('sukur-kisa-01','Sukur Duasi (Kisa)','SUKUR','GELENEKSEL',
     'Kaynak notu: Genel sukur ifadesi.',
     NULL,
     'Allahim, verdigin nimetler icin sana sukrederim; kalbime kanaat ve farkindalik ver.',
     'Nimetleri hatirlama ve sukur bilincini tazeleme niyeti.',
     7,20,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('korunma-orta-01','Korunma Duasi (Orta)','KORUNMA','GELENEKSEL',
     'Kaynak notu: Korunma temali genel dua metni; editoryal kontrol onerilir.',
     NULL,
     'Allahim, beni ve sevdiklerimi gorunen ve gorunmeyen serlerden muhafaza eyle.',
     'Korunma ve emniyet niyetiyle okunan genel dua metni.',
     3,55,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),
    ('huzur-kisa-01','Huzur Duasi (Kisa)','HUZUR','GELENEKSEL',
     'Kaynak notu: Huzur ve sakinlesme odakli kisa dua.',
     NULL,
     'Allahim, kalbime sükunet, zihnime berraklik ve davranislara nezaket ver.',
     'Icin sakinlesmesi ve zihinsel berraklik niyeti.',
     11,18,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('bereket-orta-01','Bereket Duasi (Orta)','BEREKET','GELENEKSEL',
     'Kaynak notu: Bereket ve helal rizik niyeti.',
     NULL,
     'Allahim, rizkimi helal ve bereketli kil; emegime fayda ve kolaylik ihsan eyle.',
     'Rizik, emek ve zaman bereketi niyetiyle dua.',
     3,60,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),

    ('sabah-niyet-kisa-02','Sabah Niyet Duasi','SABAH_AKSAM','GELENEKSEL',
     'Kaynak notu: Gune niyetle baslama metni.',
     NULL,
     'Allahim, bugunku sozlerimi, niyetimi ve emeğimi hayra vesile kil.',
     'Gunun niyetini hayir uzerine kurmaya yardimci kisa metin.',
     7,22,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('aksam-muhasebe-kisa-01','Aksam Muhasebe Duasi','SABAH_AKSAM','GELENEKSEL',
     'Kaynak notu: Aksam tefekkuru ve muhasebe niyeti.',
     NULL,
     'Allahim, bugunun eksiklerini gormeyi, hatalarim icin af dilemeyi ve yarina daha guzel hazirlanmayi nasip eyle.',
     'Aksam ic muhasebesi ve tevazu niyeti.',
     3,40,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),
    ('sukur-detay-01','Nimetleri Hatirlama Duasi','SUKUR','GELENEKSEL',
     'Kaynak notu: Sukur odakli genis metin.',
     NULL,
     'Allahim, unuttugum nimetleri fark etmeyi, elimdekine razi olmayi ve paylasmayi nasip eyle.',
     'Sukur bilincini derinlestirme niyetli dua.',
     3,48,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),
    ('korunma-kisa-02','Gunluk Korunma Niyeti','KORUNMA','GELENEKSEL',
     'Kaynak notu: Kisa korunma ifadesi.',
     NULL,
     'Allahim, beni dogru olandan ayirma; adimlarimi hayirli olana yonelt ve kotulukten sakindir.',
     'Gunun icinde korunma ve istikamet niyeti.',
     11,24,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('huzur-orta-02','Ic Sakinligi Duasi','HUZUR','GELENEKSEL',
     'Kaynak notu: Duygusal denge odakli genel dua.',
     NULL,
     'Allahim, telasimi azalt, sabrimi artir, kalbime guven ve teslimiyet ver.',
     'Gerginlik anlarinda sakinlesme ve sabir niyeti.',
     7,35,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),
    ('bereket-kisa-02','Is ve Zaman Bereketi Duasi','BEREKET','GELENEKSEL',
     'Kaynak notu: Is/uretim bereketi niyeti.',
     NULL,
     'Allahim, zamanimi verimli, emegimi faydali ve kazancimi bereketli kil.',
     'Gunluk is ve zaman yonetimine bereket niyeti.',
     11,19,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('hastalik-sifa-niyeti-01','Sifa ve Sabir Niyeti','HASTALIK','GELENEKSEL',
     'Kaynak notu: Tibbi vaad icermez; sabir ve sifa niyeti.',
     NULL,
     'Allahim, hastalikta sabir, tedavide kolaylik ve gonlume kuvvet ihsan eyle.',
     'Sifa dilegi ve sabir niyeti; tibbi tavsiye yerine gecmez.',
     7,28,TRUE,'Bu icerik bilgilendirme amaclidir; tibbi tavsiye degildir.',1,TRUE),
    ('kisa-destek-01','Kisa Dua: Sakinlik','KISA_DUA','GELENEKSEL',
     'Kaynak notu: 10-15 saniyelik mini dua.',
     NULL,
     'Allahim, kalbime sakinlik ver.',
     'Anlik sakinlesme niyetli mini dua.',
     3,10,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('kisa-destek-02','Kisa Dua: Sukur','KISA_DUA','GELENEKSEL',
     'Kaynak notu: 10-15 saniyelik mini dua.',
     NULL,
     'Allahim, verdiklerin icin sana sukrederim.',
     'Anlik sukur niyetli mini dua.',
     3,11,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('kisa-destek-03','Kisa Dua: Korunma','KISA_DUA','GELENEKSEL',
     'Kaynak notu: 10-20 saniyelik mini dua.',
     NULL,
     'Allahim, beni ve sevdiklerimi muhafaza eyle.',
     'Anlik korunma niyetiyle mini dua.',
     3,12,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('kisa-destek-04','Kisa Dua: Bereket','KISA_DUA','GELENEKSEL',
     'Kaynak notu: 10-20 saniyelik mini dua.',
     NULL,
     'Allahim, rizkime ve vaktime bereket ver.',
     'Kisa bereket niyetli mini dua.',
     3,12,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('kisa-destek-05','Kisa Dua: Niyet','KISA_DUA','GELENEKSEL',
     'Kaynak notu: 10-20 saniyelik mini dua.',
     NULL,
     'Allahim, niyetimi hayirli kil.',
     'Gune veya ise baslarken kisa niyet duasi.',
     3,10,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE),
    ('tevbe-istigfar-niyeti-01','Istigfar ve Yenilenme Niyeti','HUZUR','GELENEKSEL',
     'Kaynak notu: Tevazu ve yenilenme temali genel metin.',
     NULL,
     'Allahim, eksiklerimi fark etmeyi, gonlumde arinmayi ve daha guzel davranislara yonelmeyi nasip eyle.',
     'Kendini duzeltme ve ic yenilenme niyeti.',
     33,38,TRUE,'Bu icerik bilgilendirme amaclidir.',2,TRUE),
    ('yolculuk-niyeti-01','Yolculuk Oncesi Niyet Duasi','KORUNMA','GELENEKSEL',
     'Kaynak notu: Yolculuk guvenligi icin genel niyet metni.',
     NULL,
     'Allahim, yolculugumuzu emniyetli, kolay ve hayirli eyle.',
     'Yolculuk oncesi korunma ve kolaylik niyeti.',
     3,17,TRUE,'Bu icerik bilgilendirme amaclidir.',1,TRUE)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    source_label = EXCLUDED.source_label,
    source_note = EXCLUDED.source_note,
    arabic_text = EXCLUDED.arabic_text,
    transliteration_tr = EXCLUDED.transliteration_tr,
    meaning_tr = EXCLUDED.meaning_tr,
    recommended_repeat_count = EXCLUDED.recommended_repeat_count,
    estimated_read_seconds = EXCLUDED.estimated_read_seconds,
    is_favoritable = EXCLUDED.is_favoritable,
    disclaimer_text = EXCLUDED.disclaimer_text,
    difficulty_level = EXCLUDED.difficulty_level,
    active = EXCLUDED.active;

INSERT INTO asmaul_husna (
    order_no, arabic_name, transliteration_tr, meaning_tr, reflection_text_tr, theme, source_note, recommended_dhikr_count, active
) VALUES
    (1,  'الرحمن', 'Er-Rahman', 'Cok merhamet eden', 'Bugun niyetim: merhametle davranmak ve yumusak bir dil kullanmak.', 'RAHMET', 'Kaynak notu: Esma anlami kisa ozet olarak verilmiştir.', 33, TRUE),
    (2,  'الرحيم', 'Er-Rahim', 'Cok esirgeyen', 'Bugun niyetim: kendime ve baskalarina sefkatle yaklasmak.', 'RAHMET', 'Kaynak notu: Kisa anlam ve tefekkur cumlesi editoryal ozet niteligindedir.', 33, TRUE),
    (3,  'الملك', 'El-Melik', 'Mutlak hukumdar', 'Bugun niyetim: kontrol edemediklerimi teslimiyetle karsilamak.', 'HUZUR', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (4,  'القدوس', 'El-Kuddus', 'Noksanliktan uzak, mukaddes', 'Bugun niyetim: kalbimi ve niyetimi temiz tutmak.', 'ARINMA', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (5,  'السلام', 'Es-Selam', 'Esenlik veren', 'Bugun niyetim: cevreme huzur ve guven veren bir dil tasimak.', 'HUZUR', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (6,  'المؤمن', 'El-Mumin', 'Guven veren', 'Bugun niyetim: guvenilir ve dogru olmaya dikkat etmek.', 'KORUMA', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (7,  'المهيمن', 'El-Muheymin', 'Gozetip koruyan', 'Bugun niyetim: dikkatli olmak ve emanet bilinciyle hareket etmek.', 'KORUMA', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (8,  'العزيز', 'El-Aziz', 'Mutlak izzet sahibi', 'Bugun niyetim: onurumu korurken kibirden uzak durmak.', 'GUCLENME', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (9,  'الجبار', 'El-Cebbar', 'Eksikleri gideren, kudret sahibi', 'Bugun niyetim: kirik hissettigim alanlarda toparlanma icin sabir gostermek.', 'GUCLENME', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (10, 'المتكبر', 'El-Mutekebbir', 'Buyuklugunde esit olmayan', 'Bugun niyetim: hakikatin buyuklugunu hatirlayip tevazu ile kalmak.', 'TEFEKKUR', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (11, 'الخالق', 'El-Halik', 'Yaratan', 'Bugun niyetim: hayata ve kendime emanet bilinciyle bakmak.', 'TEFEKKUR', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (12, 'البارئ', 'El-Bari', 'Kusursuz yaratan', 'Bugun niyetim: duzen ve olcululuge dikkat etmek.', 'ODAK', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (13, 'المصور', 'El-Musavvir', 'Sekil veren', 'Bugun niyetim: iyi niyetle guzel davranislar insa etmek.', 'ODAK', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (14, 'الغفار', 'El-Gaffar', 'Cok bagislayan', 'Bugun niyetim: hatalarimi gormek ve bagislanma dilemek.', 'ARINMA', 'Kaynak notu: Kisa ozet.', 100, TRUE),
    (15, 'القهار', 'El-Kahhar', 'Mutlak galip', 'Bugun niyetim: nefsimin tas kinliklarini fark edip kontrol etmek.', 'OZ_DISIPLIN', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (16, 'الوهاب', 'El-Vehhab', 'Karsiliksiz ihsan eden', 'Bugun niyetim: kucuk de olsa iyilikte bulunmak.', 'BEREKET', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (17, 'الرزاق', 'Er-Rezzak', 'Rizik veren', 'Bugun niyetim: helal emek ve kanaat bilincini tazelemek.', 'RIZIK', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (18, 'الفتاح', 'El-Fettah', 'Hayirli kapilar acan', 'Bugun niyetim: zorlukta kapilarin acilabilecegini hatirlamak.', 'UMUT', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (19, 'العليم', 'El-Alim', 'Her seyi bilen', 'Bugun niyetim: bilmedigim konularda tevazu ve ogrenme istegi tasimak.', 'ILIM', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (20, 'القابض', 'El-Kabid', 'Daraltan (hikmetle)', 'Bugun niyetim: darlik anlarinda sabir ve hikmet aramak.', 'SABIR', 'Kaynak notu: Kisa ozet.', 33, TRUE),
    (21, 'الباسط', 'El-Basit', 'Genisleten', 'Bugun niyetim: ferahlik anlarinda sukru artirmak.', 'FERAHLIK', 'Kaynak notu: Kisa ozet.', 33, TRUE)
ON CONFLICT (order_no) DO UPDATE SET
    arabic_name = EXCLUDED.arabic_name,
    transliteration_tr = EXCLUDED.transliteration_tr,
    meaning_tr = EXCLUDED.meaning_tr,
    reflection_text_tr = EXCLUDED.reflection_text_tr,
    theme = EXCLUDED.theme,
    source_note = EXCLUDED.source_note,
    recommended_dhikr_count = EXCLUDED.recommended_dhikr_count,
    active = EXCLUDED.active;

INSERT INTO meditation_exercises (
    slug, title, type, focus_theme, duration_sec, steps_json, breathing_pattern_json, animation_mode,
    background_audio_enabled_by_default, disclaimer_text, difficulty_level, active
) VALUES
    ('box-breathing-4-4-4-4-2min','Kutusal Nefes 4-4-4-4','BREATHING','SAKINLESME',120,
     '[{"order":1,"text":"Dik otur ve omuzlarini gevset."},{"order":2,"text":"4 sn nefes al."},{"order":3,"text":"4 sn tut."},{"order":4,"text":"4 sn ver."},{"order":5,"text":"4 sn bekle ve donguyu tekrar et."}]',
     '{"inhale":4,"hold1":4,"exhale":4,"hold2":4}','BOX',FALSE,
     'Bu egzersiz nefes ve farkindalik amaclidir; tibbi tavsiye degildir.',1,TRUE),
    ('nefes-4-7-8-3min','Nefes 4-7-8 (3 dk)','BREATHING','SAKINLESME',180,
     '[{"order":1,"text":"Rahat bir pozisyonda otur."},{"order":2,"text":"4 sn nefes al."},{"order":3,"text":"7 sn tut."},{"order":4,"text":"8 sn yavasca ver."}]',
     '{"inhale":4,"hold1":7,"exhale":8}','RING',FALSE,
     'Bu egzersiz nefes ve farkindalik amaclidir; tibbi tavsiye degildir.',2,TRUE),
    ('nefes-3-3-6-2min','Denge Nefesi 3-3-6','BREATHING','ODAK',120,
     '[{"order":1,"text":"Burundan 3 sn nefes al."},{"order":2,"text":"3 sn bekle."},{"order":3,"text":"6 sn ver."},{"order":4,"text":"Omuzlarini gevsetip donguyu surdur."}]',
     '{"inhale":3,"hold1":3,"exhale":6}','WAVE',FALSE,
     'Bu egzersiz nefes ve farkindalik amaclidir; tibbi tavsiye degildir.',1,TRUE),
    ('sukur-odagi-2min','Sukur Odagi (2 dk)','MEDITATION','SUKUR',120,
     '[{"order":1,"text":"3 nefes dongusu ile sakinles."},{"order":2,"text":"Bugunden 3 nimet hatirla."},{"order":3,"text":"Her biri icin icinden tesekkur et."}]',
     NULL,'SOFT',FALSE,
     'Bu icerik nefes ve farkindalik egzersizidir; dini hukum veya tibbi tavsiye degildir.',1,TRUE),
    ('niyet-odagi-5min','Niyet Odagi (5 dk)','MEDITATION','NIYET',300,
     '[{"order":1,"text":"Rahat otur ve nefesi izle."},{"order":2,"text":"Bugun icin tek bir hayirli niyet belirle."},{"order":3,"text":"Bu niyeti 2-3 cumle ile netlestir."},{"order":4,"text":"Uygulanabilir bir ilk adim sec."}]',
     NULL,'SOFT',FALSE,
     'Bu icerik nefes ve farkindalik egzersizidir; dini hukum veya tibbi tavsiye degildir.',2,TRUE),
    ('beden-tarama-5min','Beden Tarama (5 dk)','BODY_SCAN','SAKINLESME',300,
     '[{"order":1,"text":"Gozlerini yumup nefesi takip et."},{"order":2,"text":"Bas-boyun-omuz bolgesini fark et."},{"order":3,"text":"Gerginlik gordugun bolgelere nefesi yonelt."},{"order":4,"text":"Ayaklara kadar yavasca taramayi tamamla."}]',
     NULL,'SOFT',FALSE,
     'Bu icerik farkindalik egzersizidir; tibbi tavsiye degildir.',2,TRUE),
    ('odak-nefesi-1min','Mini Odak Nefesi (1 dk)','BREATHING','ODAK',60,
     '[{"order":1,"text":"4 sn al, 4 sn ver."},{"order":2,"text":"Nefes sayisini 1-8 arasi takip et."},{"order":3,"text":"Zihin dagilinca nazikce nefese don."}]',
     '{"inhale":4,"exhale":4}','RING',FALSE,
     'Bu egzersiz nefes ve farkindalik amaclidir; tibbi tavsiye degildir.',1,TRUE)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    type = EXCLUDED.type,
    focus_theme = EXCLUDED.focus_theme,
    duration_sec = EXCLUDED.duration_sec,
    steps_json = EXCLUDED.steps_json,
    breathing_pattern_json = EXCLUDED.breathing_pattern_json,
    animation_mode = EXCLUDED.animation_mode,
    background_audio_enabled_by_default = EXCLUDED.background_audio_enabled_by_default,
    disclaimer_text = EXCLUDED.disclaimer_text,
    difficulty_level = EXCLUDED.difficulty_level,
    active = EXCLUDED.active;

