import {
  BIRTH_CHART_TUTORIAL_TARGET_KEYS,
  COMPATIBILITY_TUTORIAL_TARGET_KEYS,
  COSMIC_PLANNER_TUTORIAL_TARGET_KEYS,
  DAILY_TRANSITS_TUTORIAL_TARGET_KEYS,
  DECISION_COMPASS_TUTORIAL_TARGET_KEYS,
  DREAMS_TUTORIAL_TARGET_KEYS,
  GLOBAL_ONBOARDING_TARGET_KEYS,
  HOME_TUTORIAL_TARGET_KEYS,
  NAME_ANALYSIS_TUTORIAL_TARGET_KEYS,
  NUMEROLOGY_TUTORIAL_TARGET_KEYS,
  PROFILE_TUTORIAL_TARGET_KEYS,
  SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS,
  TUTORIAL_IDS,
  TUTORIAL_SCREEN_KEYS,
} from '../domain/tutorial.constants';
import type { TutorialDefinition, TutorialDisplayRule } from '../domain/tutorial.types';

const SCREEN_BASE_RULES: TutorialDisplayRule[] = [
  {
    ruleId: 'first-screen-visit',
    trigger: 'first_screen_visit',
    frequency: 'once_per_version',
  },
  {
    ruleId: 'version-changed',
    trigger: 'version_changed',
    frequency: 'once_per_version',
    allowIfCompleted: true,
    allowIfSkipped: true,
  },
  {
    ruleId: 'manual-reopen',
    trigger: 'manual_reopen',
    frequency: 'always',
    allowIfCompleted: true,
    allowIfSkipped: true,
  },
];

const GLOBAL_ONBOARDING_RULES: TutorialDisplayRule[] = [
  {
    ruleId: 'global-first-app-open',
    trigger: 'first_app_open',
    frequency: 'once_per_version',
  },
  {
    ruleId: 'global-version-changed',
    trigger: 'version_changed',
    frequency: 'once_per_version',
    allowIfCompleted: true,
    allowIfSkipped: true,
  },
  {
    ruleId: 'global-manual-reopen',
    trigger: 'manual_reopen',
    frequency: 'always',
    allowIfCompleted: true,
    allowIfSkipped: true,
  },
];

const NOW = '2026-03-09T00:00:00.000Z';

export const localTutorialRegistry: TutorialDefinition[] = [
  {
    tutorialId: TUTORIAL_IDS.GLOBAL_ONBOARDING,
    name: 'Global Onboarding',
    screenKey: TUTORIAL_SCREEN_KEYS.GLOBAL_ONBOARDING,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 1000,
    order: 1,
    presentationType: 'fullscreen_carousel',
    analyticsKey: 'global_onboarding',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: GLOBAL_ONBOARDING_RULES,
    targets: [
      {
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        screenKey: TUTORIAL_SCREEN_KEYS.GLOBAL_ONBOARDING,
        shape: 'rounded_rect',
        padding: 0,
        cornerRadius: 30,
      },
    ],
    steps: [
      {
        stepId: 'welcome',
        order: 1,
        title: 'Hoş Geldin',
        body: 'Sana özel astrolojik rehberlik, planlama ve içgörü deneyimine hoş geldin.',
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        iconKey: 'sparkles-outline',
        presentationType: 'fullscreen_carousel',
        isActive: true,
        analyticsKey: 'welcome',
      },
      {
        stepId: 'daily-guidance',
        order: 2,
        title: 'Günlük Rehberlik',
        body: 'Günün enerjisini, transitleri ve öne çıkan etkileri burada takip edersin.',
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        iconKey: 'sunny-outline',
        presentationType: 'fullscreen_carousel',
        isActive: true,
        analyticsKey: 'daily_guidance',
      },
      {
        stepId: 'planning-and-decisions',
        order: 3,
        title: 'Planlama ve Karar',
        body: 'Kozmik Planlayıcı ve Karar Pusulası ile uygun zamanları ve seçenekleri değerlendirebilirsin.',
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        iconKey: 'compass-outline',
        presentationType: 'fullscreen_carousel',
        isActive: true,
        analyticsKey: 'planning_and_decisions',
      },
      {
        stepId: 'compatibility-and-discovery',
        order: 4,
        title: 'Uyum ve Keşif',
        body: 'Uyum analizi, rüya, numeroloji ve diğer modüllerle kendini daha yakından keşfedebilirsin.',
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        iconKey: 'planet-outline',
        presentationType: 'fullscreen_carousel',
        isActive: true,
        analyticsKey: 'compatibility_and_discovery',
      },
      {
        stepId: 'lets-start',
        order: 5,
        title: 'Başla',
        body: 'Modüllere girdikçe kısa rehberler seni karşılayacak.',
        targetKey: GLOBAL_ONBOARDING_TARGET_KEYS.INTRO,
        iconKey: 'rocket-outline',
        presentationType: 'fullscreen_carousel',
        isActive: true,
        analyticsKey: 'lets_start',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.HOME_FOUNDATION,
    name: 'Home Foundation Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.HOME,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 900,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'home_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: HOME_TUTORIAL_TARGET_KEYS.HERO_ENERGY,
        screenKey: TUTORIAL_SCREEN_KEYS.HOME,
        shape: 'rounded_rect',
        padding: 12,
        cornerRadius: 24,
      },
      {
        targetKey: HOME_TUTORIAL_TARGET_KEYS.QUICK_ACTIONS,
        screenKey: TUTORIAL_SCREEN_KEYS.HOME,
        shape: 'rounded_rect',
        padding: 12,
        cornerRadius: 24,
      },
      {
        targetKey: HOME_TUTORIAL_TARGET_KEYS.PERSONAL_WIDGET,
        screenKey: TUTORIAL_SCREEN_KEYS.HOME,
        shape: 'rounded_rect',
        padding: 12,
        cornerRadius: 24,
      },
      {
        targetKey: HOME_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.HOME,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
    ],
    steps: [
      {
        stepId: 'hero-energy',
        order: 1,
        title: 'Günün Enerjisi',
        body: 'Bugünün enerjisini burada kısa ve sade biçimde görürsün.',
        targetKey: HOME_TUTORIAL_TARGET_KEYS.HERO_ENERGY,
        iconKey: 'sunny-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'hero_energy',
      },
      {
        stepId: 'quick-actions',
        order: 2,
        title: 'Ana Modül Kısayolları',
        body: 'En çok kullanılan modüllere buradan hızlıca geçebilirsin.',
        targetKey: HOME_TUTORIAL_TARGET_KEYS.QUICK_ACTIONS,
        iconKey: 'rocket-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'quick_actions',
      },
      {
        stepId: 'personal-widget',
        order: 3,
        title: 'Sana Özel Öneriler',
        body: 'Sana özel içgörüler ve öneriler burada öne çıkar.',
        targetKey: HOME_TUTORIAL_TARGET_KEYS.PERSONAL_WIDGET,
        iconKey: 'sparkles-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'personal_widget',
      },
      {
        stepId: 'module-guides',
        order: 4,
        title: 'Diğer Rehberler',
        body: 'Diğer rehberleri modüllere girdikçe göreceksin.',
        targetKey: HOME_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'navigate-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'module_guides',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.DAILY_TRANSITS_FOUNDATION,
    name: 'Daily Transits Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.DAILY_TRANSITS,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 700,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'daily_transits_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.HERO_SUMMARY,
        screenKey: TUTORIAL_SCREEN_KEYS.DAILY_TRANSITS,
        shape: 'rounded_rect',
        padding: 12,
        cornerRadius: 24,
      },
      {
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.TRANSIT_CARDS,
        screenKey: TUTORIAL_SCREEN_KEYS.DAILY_TRANSITS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.IMPACT_ZONES,
        screenKey: TUTORIAL_SCREEN_KEYS.DAILY_TRANSITS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DAILY_TRANSITS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'daily-summary',
        order: 1,
        title: 'Günün Özeti',
        body: 'Bugünün gökyüzü etkilerini burada kısa ve anlaşılır biçimde görürsün.',
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.HERO_SUMMARY,
        iconKey: 'sunny-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'daily_summary',
      },
      {
        stepId: 'transit-cards',
        order: 2,
        title: 'Transit Kartları',
        body: 'Transit kartları günün öne çıkan etkilerini sırayla açıklar.',
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.TRANSIT_CARDS,
        iconKey: 'planet-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'transit_cards',
      },
      {
        stepId: 'impact-zones',
        order: 3,
        title: 'Etki Alanları',
        body: 'Destekleyici ve dikkat gerektiren alanlar kararlarını daha bilinçli yorumlamana yardım eder.',
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.IMPACT_ZONES,
        iconKey: 'flash-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'impact_zones',
      },
      {
        stepId: 'help-reopen',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'Dilediğinde buradan bu rehberi tekrar başlatabilirsin.',
        targetKey: DAILY_TRANSITS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_reopen',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.COSMIC_PLANNER_INTRO,
    name: 'Cosmic Planner Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 680,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'cosmic_planner_intro',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.DATE_PICKER,
        screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.CATEGORY_DOCK,
        screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.DAILY_RECOMMENDATIONS,
        screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.REMINDER_ACTION,
        screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
      {
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.COSMIC_PLANNER,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'date-selection',
        order: 1,
        title: 'Tarih Seçimi',
        body: 'Hangi gün hangi konuya odaklanmanın daha uygun olduğunu burada görürsün.',
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.DATE_PICKER,
        iconKey: 'calendar-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'date_selection',
      },
      {
        stepId: 'category-dock',
        order: 2,
        title: 'Kategori Dock',
        body: 'Kategori seçerek aşk, iş, iletişim gibi alanlara odaklanabilirsin.',
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.CATEGORY_DOCK,
        iconKey: 'albums-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'category_dock',
      },
      {
        stepId: 'daily-recommendations',
        order: 3,
        title: 'Günlük Öneriler',
        body: 'Günlük öneriler planlarını gökyüzü ritmine göre şekillendirmen için tasarlandı.',
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.DAILY_RECOMMENDATIONS,
        iconKey: 'sparkles-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'daily_recommendations',
      },
      {
        stepId: 'reminder-action',
        order: 4,
        title: 'Hatırlatıcı ve Plan',
        body: 'Hatırlatıcılarla uygun zamanı kaçırmadan planını takip edebilirsin.',
        targetKey: COSMIC_PLANNER_TUTORIAL_TARGET_KEYS.REMINDER_ACTION,
        iconKey: 'alarm-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'reminder_action',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.DECISION_COMPASS_INTRO,
    name: 'Decision Compass Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 660,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'decision_compass_intro',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.HEADER_SUMMARY,
        screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 20,
      },
      {
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.INPUT_AREA,
        screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
      {
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.RESULT_AREA,
        screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.REEVALUATE_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
      {
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DECISION_COMPASS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'decision-input',
        order: 1,
        title: 'Karar Giriş Alanı',
        body: 'Burada seçeneklerini karşılaştırarak günün etkileriyle birlikte değerlendirebilirsin.',
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.INPUT_AREA,
        iconKey: 'list-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'decision_input',
      },
      {
        stepId: 'result-comparison',
        order: 2,
        title: 'Sonuç Karşılaştırma',
        body: 'Sonuç alanı kesin hüküm vermez; kararını destekleyen bir rehber sunar.',
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.RESULT_AREA,
        iconKey: 'stats-chart-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'result_comparison',
      },
      {
        stepId: 'insight-commentary',
        order: 3,
        title: 'İçgörü Yorumları',
        body: 'Yorumlar, seçeneklerin güçlü ve zayıf taraflarını daha net görmene yardım eder.',
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.HEADER_SUMMARY,
        iconKey: 'reader-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'insight_commentary',
      },
      {
        stepId: 'reevaluate-entry',
        order: 4,
        title: 'Yeniden Değerlendir',
        body: 'Kategorilerini güncelleyip daha sonra yeniden değerlendirebilirsin.',
        targetKey: DECISION_COMPASS_TUTORIAL_TARGET_KEYS.REEVALUATE_ENTRY,
        iconKey: 'options-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'reevaluate_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.COMPATIBILITY_FOUNDATION,
    name: 'Compatibility Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 640,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'compatibility_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SUMMARY_HEADER,
        screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 20,
      },
      {
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SECTION_TABS,
        screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SCORE_AREA,
        screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SAVE_SHARE_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.COMPATIBILITY,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'compatibility-summary',
        order: 1,
        title: 'Uyum Özeti',
        body: 'Genel uyum özetini burada hızlıca görürsün.',
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SUMMARY_HEADER,
        iconKey: 'heart-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'compatibility_summary',
      },
      {
        stepId: 'sections-and-details',
        order: 2,
        title: 'Özet ve Detay',
        body: 'Kişi ve ilişki alanlarını birlikte inceleyerek daha net yorum yapabilirsin.',
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SECTION_TABS,
        iconKey: 'grid-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'sections_and_details',
      },
      {
        stepId: 'category-score-cards',
        order: 3,
        title: 'Kategori Kartları',
        body: 'Skorların yanında açıklamalar ve öneriler de sunulur; yalnızca sayı gösterilmez.',
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SCORE_AREA,
        iconKey: 'analytics-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'category_score_cards',
      },
      {
        stepId: 'save-and-share',
        order: 4,
        title: 'Kaydet ve Paylaş',
        body: 'Analizi başlatıp sonuçları daha sonra yeniden değerlendirebilir ve paylaşabilirsin.',
        targetKey: COMPATIBILITY_TUTORIAL_TARGET_KEYS.SAVE_SHARE_ENTRY,
        iconKey: 'share-social-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'save_and_share',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.BIRTH_CHART_INTRO,
    name: 'Birth Chart Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 630,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'birth_chart_intro',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.HERO_SUMMARY,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.PLANET_POSITIONS,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.TECHNICAL_DETAILS,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.INSIGHT_PANEL,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.DETAIL_ACTION,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
      {
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.BIRTH_CHART,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'hero-summary',
        order: 1,
        title: 'Harita Özeti',
        body: 'Doğum haritanın genel özetini burada hızlıca görebilirsin.',
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.HERO_SUMMARY,
        iconKey: 'planet-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'hero_summary',
      },
      {
        stepId: 'main-placements',
        order: 2,
        title: 'Ana Yerleşimler',
        body: 'Ana yerleşimler, karakterini ve eğilimlerini anlamana yardımcı olur.',
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.PLANET_POSITIONS,
        iconKey: 'sparkles-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'main_placements',
      },
      {
        stepId: 'technical-details',
        order: 3,
        title: 'Teknik Detaylar',
        body: 'Detay alanlarında evler, burçlar ve teknik katmanları inceleyebilirsin.',
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.TECHNICAL_DETAILS,
        iconKey: 'grid-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'technical_details',
      },
      {
        stepId: 'insight-cards',
        order: 4,
        title: 'Yorum Kartları',
        body: 'Yorum kartları haritandaki bilgileri daha sade ve anlaşılır hale getirir.',
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.INSIGHT_PANEL,
        iconKey: 'reader-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'insight_cards',
      },
      {
        stepId: 'detail-actions',
        order: 5,
        title: 'Kaydet ve İncele',
        body: 'İstersen bu alanı kaydedebilir, paylaşabilir ya da daha detaylı inceleyebilirsin.',
        targetKey: BIRTH_CHART_TUTORIAL_TARGET_KEYS.DETAIL_ACTION,
        iconKey: 'share-social-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'detail_actions',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.DREAMS_FOUNDATION,
    name: 'Dreams Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.DREAMS,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 620,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'dreams_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.COMPOSE_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DREAMS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 20,
      },
      {
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.INTERPRETATION_RESULT,
        screenKey: TUTORIAL_SCREEN_KEYS.DREAMS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.HISTORY_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DREAMS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
      {
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.DREAMS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'dream-entry',
        order: 1,
        title: 'Rüya Girişi',
        body: 'Rüyanı yazarak sembolik bir yorum alırsın.',
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.COMPOSE_ENTRY,
        iconKey: 'create-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'dream_entry',
      },
      {
        stepId: 'interpretation-result',
        order: 2,
        title: 'Yorum Sonucu',
        body: 'Yorum sonucu içgörü ve farkındalık için tasarlandı.',
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.INTERPRETATION_RESULT,
        iconKey: 'moon-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'interpretation_result',
      },
      {
        stepId: 'history-entry',
        order: 3,
        title: 'Geçmiş Kayıtlar',
        body: 'Önceki rüya kayıtlarına dönüp tekrar bakabilir, gelişimini takip edebilirsin.',
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.HISTORY_ENTRY,
        iconKey: 'time-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'history_entry',
      },
      {
        stepId: 'help-entry',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'İstediğinde rehberi bu ekrandan yeniden başlatabilirsin.',
        targetKey: DREAMS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.NUMEROLOGY_FOUNDATION,
    name: 'Numerology Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.NUMEROLOGY,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 610,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'numerology_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.INPUT_AREA,
        screenKey: TUTORIAL_SCREEN_KEYS.NUMEROLOGY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.RESULT_CARD,
        screenKey: TUTORIAL_SCREEN_KEYS.NUMEROLOGY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.DETAIL_SECTION,
        screenKey: TUTORIAL_SCREEN_KEYS.NUMEROLOGY,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.NUMEROLOGY,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'numerology-input',
        order: 1,
        title: 'Giriş Alanı',
        body: 'Sayıların sembolik anlamlarını burada keşfedersin.',
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.INPUT_AREA,
        iconKey: 'calculator-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'numerology_input',
      },
      {
        stepId: 'numerology-result',
        order: 2,
        title: 'Sonuç Kartı',
        body: 'Ana sayı profilin ve güncel tema burada kısa bir özetle öne çıkar.',
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.RESULT_CARD,
        iconKey: 'analytics-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'numerology_result',
      },
      {
        stepId: 'numerology-detail',
        order: 3,
        title: 'Detay Açıklamalar',
        body: 'Detay kartları kişisel sayılarını daha derin ve anlaşılır biçimde açıklar.',
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.DETAIL_SECTION,
        iconKey: 'reader-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'numerology_detail',
      },
      {
        stepId: 'help-entry',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'Dilediğinde rehberi manuel olarak yeniden başlatabilirsin.',
        targetKey: NUMEROLOGY_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.NAME_ANALYSIS_FOUNDATION,
    name: 'Name Analysis Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.NAME_ANALYSIS,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 600,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'name_analysis_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.NAME_INPUT,
        screenKey: TUTORIAL_SCREEN_KEYS.NAME_ANALYSIS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.MEANING_PANEL,
        screenKey: TUTORIAL_SCREEN_KEYS.NAME_ANALYSIS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.SAVE_SHARE_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.NAME_ANALYSIS,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.NAME_ANALYSIS,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'name-input',
        order: 1,
        title: 'İsim Giriş Alanı',
        body: 'İsmini girerek anlam ve sembolik çağrışımlarını keşfetmeye başlarsın.',
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.NAME_INPUT,
        iconKey: 'search-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'name_input',
      },
      {
        stepId: 'meaning-panel',
        order: 2,
        title: 'Anlam ve Köken',
        body: 'İsmin anlamını ve sembolik çağrışımlarını burada görürsün.',
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.MEANING_PANEL,
        iconKey: 'book-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'meaning_panel',
      },
      {
        stepId: 'save-share',
        order: 3,
        title: 'Kaydet ve Favorile',
        body: 'Beğendiğin isimleri kaydedebilir ve daha sonra hızlıca geri dönebilirsin.',
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.SAVE_SHARE_ENTRY,
        iconKey: 'bookmark-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'save_share',
      },
      {
        stepId: 'help-entry',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'Rehberi ihtiyaç duyduğunda bu ekrandan yeniden açabilirsin.',
        targetKey: NAME_ANALYSIS_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.SPIRITUAL_PRACTICE_FOUNDATION,
    name: 'Spiritual Practice Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.SPIRITUAL_PRACTICE,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 590,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'spiritual_practice_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.DAILY_RECOMMENDATION,
        screenKey: TUTORIAL_SCREEN_KEYS.SPIRITUAL_PRACTICE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.PRACTICE_COUNTER,
        screenKey: TUTORIAL_SCREEN_KEYS.SPIRITUAL_PRACTICE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.JOURNAL_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.SPIRITUAL_PRACTICE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.SPIRITUAL_PRACTICE,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'daily-recommendation',
        order: 1,
        title: 'Günün Önerisi',
        body: 'Günlük pratiğini burada takip eder, ilerlemeni kaydedebilirsin.',
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.DAILY_RECOMMENDATION,
        iconKey: 'sparkles-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'daily_recommendation',
      },
      {
        stepId: 'practice-counter',
        order: 2,
        title: 'Sayaç ve Akış',
        body: 'Dua, esma ve meditasyon akışlarını bu alandan hızlıca başlatabilirsin.',
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.PRACTICE_COUNTER,
        iconKey: 'timer-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'practice_counter',
      },
      {
        stepId: 'journal-entry',
        order: 3,
        title: 'Günlük Kaydı',
        body: 'Günlük notlarına ve ruhsal pratiğinin geçmişine buradan ulaşabilirsin.',
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.JOURNAL_ENTRY,
        iconKey: 'journal-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'journal_entry',
      },
      {
        stepId: 'help-entry',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'Rehberi tekrar görmek için bu yardım alanını kullanabilirsin.',
        targetKey: SPIRITUAL_PRACTICE_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    tutorialId: TUTORIAL_IDS.PROFILE_FOUNDATION,
    name: 'Profile Tutorial',
    screenKey: TUTORIAL_SCREEN_KEYS.PROFILE,
    version: 1,
    isActive: true,
    platform: 'ALL',
    priority: 580,
    order: 1,
    presentationType: 'spotlight_card',
    analyticsKey: 'profile_foundation',
    publishStatus: 'published',
    source: 'local_static',
    resolvedSource: 'local',
    startAt: null,
    endAt: null,
    displayRules: SCREEN_BASE_RULES,
    targets: [
      {
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.PERSONAL_INFO,
        screenKey: TUTORIAL_SCREEN_KEYS.PROFILE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 22,
      },
      {
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.PREFERENCES,
        screenKey: TUTORIAL_SCREEN_KEYS.PROFILE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 20,
      },
      {
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.TUTORIAL_CENTER_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.PROFILE,
        shape: 'rounded_rect',
        padding: 10,
        cornerRadius: 18,
      },
      {
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        screenKey: TUTORIAL_SCREEN_KEYS.PROFILE,
        shape: 'rounded_rect',
        padding: 8,
        cornerRadius: 18,
      },
    ],
    steps: [
      {
        stepId: 'personal-info',
        order: 1,
        title: 'Kişisel Bilgiler',
        body: 'Profil bilgilerini bu alanda güncelleyebilir ve deneyimini kişiselleştirebilirsin.',
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.PERSONAL_INFO,
        iconKey: 'person-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'personal_info',
      },
      {
        stepId: 'preferences',
        order: 2,
        title: 'Güvenlik ve Tercihler',
        body: 'Bildirim, tema ve güvenlik ayarlarını buradan kolayca yönetebilirsin.',
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.PREFERENCES,
        iconKey: 'settings-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'preferences',
      },
      {
        stepId: 'tutorial-center-entry',
        order: 3,
        title: 'Rehber Merkezi',
        body: 'Tüm onboarding ve modül rehberlerini tek yerden yönetebilirsin.',
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.TUTORIAL_CENTER_ENTRY,
        iconKey: 'albums-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'tutorial_center_entry',
      },
      {
        stepId: 'help-entry',
        order: 4,
        title: 'Rehberi Tekrar Aç',
        body: 'Profil rehberini dilediğinde yeniden başlatabilirsin.',
        targetKey: PROFILE_TUTORIAL_TARGET_KEYS.HELP_ENTRY,
        iconKey: 'help-circle-outline',
        presentationType: 'spotlight_card',
        isActive: true,
        analyticsKey: 'help_entry',
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export function getLocalTutorialById(tutorialId: string): TutorialDefinition | null {
  return localTutorialRegistry.find((tutorial) => tutorial.tutorialId === tutorialId) ?? null;
}

export function getLocalTutorialsByScreen(screenKey: string): TutorialDefinition[] {
  return localTutorialRegistry
    .filter((tutorial) => tutorial.screenKey === screenKey)
    .sort((left, right) => right.priority - left.priority || left.order - right.order);
}
