import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Image,
  Linking,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { AppHeader, SafeScreen } from '../../components/ui';
import * as Haptics from '../../utils/haptics';
import ViewShot from 'react-native-view-shot';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import MatchCard from '../../components/match/MatchCard';
import { useMatchCardStore } from '../../store/useMatchCardStore';
import { useGenerateMatchImage } from '../../hooks/useGenerateMatchImage';
import {
  ShareServiceError,
  instagramStory,
  saveToGallery,
  shareImage,
} from '../../services/share.service';
import { useSmartBackNavigation } from '../../hooks/useSmartBackNavigation';

type ShareAction = 'share' | 'instagram' | 'save' | null;

const UNIVERSAL_DOWNLOAD_URL = 'https://mysticai.app/dl';
const META_INSTAGRAM_STORY_APP_ID =
  process.env.EXPO_PUBLIC_FACEBOOK_APP_ID || process.env.EXPO_PUBLIC_META_APP_ID || undefined;

export default function MatchCardPreviewScreen() {
  const { colors } = useTheme();
  const draft = useMatchCardStore((s) => s.draft);
  const goBack = useSmartBackNavigation({ fallbackRoute: '/(tabs)/home' });

  const viewShotRef = useRef<ViewShot | null>(null);
  const [layoutTick, setLayoutTick] = useState(0);
  const [actionLoading, setActionLoading] = useState<ShareAction>(null);
  const [successText, setSuccessText] = useState<string | null>(null);

  const { imageUri, loading, error, generate, retry } = useGenerateMatchImage(viewShotRef);
  const autoGeneratedForKeyRef = useRef<string | null>(null);

  const draftKey = useMemo(
    () => (draft ? `${draft.user1Name}|${draft.user2Name}|${draft.createdAt}` : null),
    [draft],
  );

  useEffect(() => {
    autoGeneratedForKeyRef.current = null;
    setSuccessText(null);
  }, [draftKey]);

  useEffect(() => {
    if (!draft || !layoutTick) return;
    if (autoGeneratedForKeyRef.current === draftKey) return;
    autoGeneratedForKeyRef.current = draftKey;
    void generate().catch(() => {
      // Error state is already handled by hook.
    });
  }, [draft, layoutTick, draftKey, generate]);

  useEffect(() => {
    if (!successText) return;
    const timer = setTimeout(() => setSuccessText(null), 1800);
    return () => clearTimeout(timer);
  }, [successText]);

  const notifySuccess = async (message: string) => {
    setSuccessText(message);
    try {
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch {
      // no-op
    }
  };

  const presentShareError = useCallback(async (title: string, cause: unknown) => {
    const error =
      cause instanceof ShareServiceError
        ? cause
        : new Error((cause as any)?.message ?? 'İşlem tamamlanamadı.');

    const openSettings = async () => {
      try {
        await Linking.openSettings();
      } catch {
        Alert.alert('Ayarlar Açılamadı', 'Lütfen Ayarlar uygulamasını manuel olarak açın.');
      }
    };

    if (error instanceof ShareServiceError && error.suggestOpenSettings) {
      Alert.alert(title, error.message, [
        { text: 'Vazgeç', style: 'cancel' },
        { text: 'Ayarları Aç', onPress: () => void openSettings() },
      ]);
      return;
    }

    Alert.alert(title, error.message);
  }, []);

  const runShareAction = async (
    action: Exclude<ShareAction, null>,
    errorTitle: string,
    fn: () => Promise<void>,
  ) => {
    if (!imageUri) return;
    setActionLoading(action);
    try {
      await fn();
    } catch (e: any) {
      await presentShareError(errorTitle, e);
    } finally {
      setActionLoading(null);
    }
  };

  const handleShare = async () => {
    await runShareAction('share', 'Paylaşım Hatası', async () => {
      await shareImage(imageUri!);
      await notifySuccess('Paylaşım ekranı açıldı');
    });
  };

  const handleSave = async () => {
    await runShareAction('save', 'Kaydetme Hatası', async () => {
      const result = await saveToGallery(imageUri!);
      await notifySuccess(result.message ?? 'Kart galeriye kaydedildi');
    });
  };

  const handleInstagram = async () => {
    await runShareAction('instagram', 'Instagram Story Hatası', async () => {
      const result = await instagramStory(imageUri!, {
        attributionURL: UNIVERSAL_DOWNLOAD_URL,
        appId: META_INSTAGRAM_STORY_APP_ID,
        fallbackToSystemShare: true,
      });
      await notifySuccess(result.fallbackUsed ? 'Sistem paylaşımı açıldı' : 'Instagram Story başlatıldı');
    });
  };

  const handleRegenerate = async () => {
    setSuccessText(null);
    try {
      await retry();
    } catch {
      // Hook already exposes error; keep UX local with alert only on explicit user action
      await presentShareError('Kart Oluşturulamadı', new Error('Kart yeniden oluşturulamadı. Lütfen tekrar deneyin.'));
    }
  };

  if (!draft) {
    return (
      <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
        <View style={styles.emptyWrap}>
          <Ionicons name="sparkles-outline" size={28} color={colors.violet} />
          <Text style={[styles.emptyTitle, { color: colors.text }]}>Yıldız kartı verisi bulunamadı</Text>
          <Text style={[styles.emptySub, { color: colors.subtext }]}>
            Önce uyum sonucu ekranından "Yıldız Kartı" butonuna dokunun.
          </Text>
          <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={goBack}>
            <Text style={styles.primaryBtnText}>Geri Dön</Text>
          </Pressable>
        </View>
      </SafeScreen>
    );
  }

  return (
    <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}>
      <View pointerEvents="none" style={styles.captureHost}>
        <ViewShot
          ref={viewShotRef}
          style={styles.captureCanvas}
          onLayout={() => setLayoutTick(Date.now())}
          options={{
            format: 'png',
            quality: 1,
            result: 'tmpfile',
            width: 1080,
            height: 2160,
          } as any}
        >
          <MatchCard
            user1Name={draft.user1Name}
            user2Name={draft.user2Name}
            user1Sign={draft.user1Sign}
            user2Sign={draft.user2Sign}
            compatibilityScore={draft.compatibilityScore}
            relationshipType={draft.relationshipType}
            relationLabel={draft.relationLabel}
            aiSummary={draft.aiSummary}
            cardSummary={draft.cardSummary}
            traitAxes={draft.traitAxes}
            aspectsCount={draft.aspectsCount}
            scoreBreakdown={draft.scoreBreakdown ?? null}
            displayMetrics={draft.displayMetrics ?? null}
          />
        </ViewShot>
      </View>

      <AppHeader
        title="Yıldız Kartı Önizleme"
        subtitle="Kart otomatik oluşturulur, sonra paylaşım seçenekleri açılır."
        onBack={goBack}
      />

      {successText ? (
        <View style={[styles.successBanner, { backgroundColor: colors.successBg, borderColor: colors.successLight }]}>
          <Ionicons name="checkmark-circle" size={16} color={colors.success} />
          <Text style={[styles.successText, { color: colors.success }]}>{successText}</Text>
        </View>
      ) : null}

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={[styles.previewShell, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          {loading ? (
            <View style={styles.loaderWrap}>
              <View style={[styles.loaderCardGhost, { backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} />
              <ActivityIndicator size="large" color={colors.violet} />
              <Text style={[styles.loaderTitle, { color: colors.text }]}>Kart oluşturuluyor…</Text>
              <Text style={[styles.loaderSub, { color: colors.subtext }]}>
                Yüksek kalite görsel hazırlanıyor. Bu işlem birkaç saniye sürebilir.
              </Text>
            </View>
          ) : imageUri ? (
            <>
              <Image source={{ uri: imageUri }} style={styles.previewImage} resizeMode="contain" />
              <Text style={[styles.previewMeta, { color: colors.subtext }]}>
                {draft.relationLabel} • {draft.compatibilityScore}% • {draft.aspectsCount} açı
              </Text>
            </>
          ) : (
            <View style={styles.errorWrap}>
              <Ionicons name="warning-outline" size={24} color={colors.warning} />
              <Text style={[styles.errorTitle, { color: colors.text }]}>Kart oluşturulamadı</Text>
              <Text style={[styles.errorSub, { color: colors.subtext }]}>
                {error ?? 'Beklenmeyen bir hata oluştu.'}
              </Text>
              <Pressable style={[styles.primaryBtn, { backgroundColor: colors.violet }]} onPress={handleRegenerate}>
                <Text style={styles.primaryBtnText}>Tekrar Dene</Text>
              </Pressable>
            </View>
          )}
        </View>

        <View style={styles.actionsBlock}>
          <Pressable
            style={[styles.regenerateBtn, { borderColor: colors.border, backgroundColor: colors.surface }]}
            onPress={handleRegenerate}
            disabled={loading || actionLoading != null}
          >
            <Ionicons name="refresh" size={16} color={colors.text} />
            <Text style={[styles.regenerateBtnText, { color: colors.text }]}>Kartı Yeniden Oluştur</Text>
          </Pressable>

          {imageUri && !loading ? (
            <>
              <Pressable
                style={[styles.primaryBtn, { backgroundColor: colors.violet }, actionLoading && styles.btnDisabled]}
                onPress={handleShare}
                disabled={actionLoading != null}
              >
                {actionLoading === 'share' ? (
                  <ActivityIndicator size="small" color="#FFF" />
                ) : (
                  <Ionicons name="share-social" size={16} color="#FFF" />
                )}
                <Text style={styles.primaryBtnText}>Paylaş</Text>
              </Pressable>

              <View style={styles.secondaryRow}>
                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleInstagram}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'instagram' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="logo-instagram" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>Instagram Story</Text>
                </Pressable>

                <Pressable
                  style={[styles.secondaryBtn, { backgroundColor: colors.surface, borderColor: colors.border }, actionLoading && styles.btnDisabled]}
                  onPress={handleSave}
                  disabled={actionLoading != null}
                >
                  {actionLoading === 'save' ? (
                    <ActivityIndicator size="small" color={colors.text} />
                  ) : (
                    <Ionicons name="download-outline" size={16} color={colors.text} />
                  )}
                  <Text style={[styles.secondaryBtnText, { color: colors.text }]}>Galeriye Kaydet</Text>
                </Pressable>
              </View>
            </>
          ) : null}
        </View>
      </ScrollView>
    </SafeScreen>
  );
}

const styles = StyleSheet.create({
  captureHost: {
    position: 'absolute',
    left: -9999,
    top: 0,
    width: 360,
    height: 720,
    opacity: 0.01,
  },
  captureCanvas: {
    width: 360,
    height: 720,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  headerTextWrap: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  headerSub: {
    fontSize: 12,
    marginTop: 2,
  },
  successBanner: {
    marginHorizontal: 16,
    marginTop: 6,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  successText: {
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 22,
    gap: 14,
  },
  previewShell: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 14,
    minHeight: 720,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loaderWrap: {
    alignItems: 'center',
    width: '100%',
  },
  loaderCardGhost: {
    width: 252,
    aspectRatio: 360 / 720,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 18,
    opacity: 0.7,
  },
  loaderTitle: {
    fontSize: 14,
    fontWeight: '800',
    marginTop: 6,
  },
  loaderSub: {
    marginTop: 4,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 18,
  },
  previewImage: {
    width: '100%',
    maxWidth: 360,
    aspectRatio: 360 / 720,
    borderRadius: 16,
    backgroundColor: '#F2E6FB',
  },
  previewMeta: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  errorWrap: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  errorTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  errorSub: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
    marginBottom: 4,
  },
  actionsBlock: {
    gap: 10,
  },
  regenerateBtn: {
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  regenerateBtnText: {
    fontSize: 13,
    fontWeight: '700',
  },
  primaryBtn: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
  },
  primaryBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
  },
  secondaryBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  btnDisabled: {
    opacity: 0.65,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptySub: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 4,
  },
});
