import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Linking,
  Pressable,
  ScrollView,
  StyleSheet,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import ViewShot from 'react-native-view-shot';
import { useLocalSearchParams } from 'expo-router';
import { AppHeader, SafeScreen, AccessibleText } from '../../components/ui';
import { useTheme } from '../../context/ThemeContext';
import { ACCESSIBILITY } from '../../constants/tokens';
import { useMatchTraits } from '../../hooks/useMatchTraits';
import MatchCard from '../../components/match/MatchCard';
import {
  getSynastry,
  type RelationshipType,
  type SynastryDisplayMetric,
  type SynastryScoreBreakdown,
} from '../../services/synastry.service';
import { toTraitAxes } from '../../services/match.api';
import { useGenerateMatchImage } from '../../hooks/useGenerateMatchImage';
import {
  ShareServiceError,
  saveToGallery,
  shareImage,
} from '../../services/share.service';
import * as Haptics from '../../utils/haptics';

type ShareAction = 'share' | 'save' | 'regenerate' | null;

function parseMatchId(value: string | string[] | undefined) {
  const raw = Array.isArray(value) ? value[0] : value;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0) return null;
  return Math.floor(n);
}

function parseRelationshipType(value: string | string[] | undefined): RelationshipType | null {
  const raw = Array.isArray(value) ? value[0] : value;
  const source = String(raw ?? '')
    .trim()
    .toLocaleLowerCase('tr-TR')
    .replace(/ç/g, 'c')
    .replace(/ğ/g, 'g')
    .replace(/ı/g, 'i')
    .replace(/ö/g, 'o')
    .replace(/ş/g, 's')
    .replace(/ü/g, 'u')
    .replace(/[^a-z0-9]+/g, '');

  const map: Record<string, RelationshipType> = {
    love: 'LOVE',
    ask: 'LOVE',
    partner: 'LOVE',
    es: 'LOVE',
    relationship: 'LOVE',
    business: 'BUSINESS',
    work: 'BUSINESS',
    is: 'BUSINESS',
    kariyer: 'BUSINESS',
    friend: 'FRIENDSHIP',
    friendship: 'FRIENDSHIP',
    arkadas: 'FRIENDSHIP',
    arkadaslik: 'FRIENDSHIP',
    family: 'FAMILY',
    aile: 'FAMILY',
    rival: 'RIVAL',
    rekabet: 'RIVAL',
    rakip: 'RIVAL',
  };

  return map[source] ?? null;
}

type SynastryCardMeta = {
  relationshipType: RelationshipType | null;
  relationLabel: string | null;
  scoreBreakdown: Pick<SynastryScoreBreakdown, 'overall' | 'love' | 'communication' | 'spiritualBond'> | null;
  displayMetrics: SynastryDisplayMetric[] | null;
};

export default function ShareCardPreviewScreen() {
  const params = useLocalSearchParams<{
    matchId?: string;
    personAName?: string;
    personBName?: string;
    personASignLabel?: string;
    personBSignLabel?: string;
    overallScore?: string;
    relationshipType?: string;
    relationLabel?: string;
  }>();

  const { colors } = useTheme();
  const matchId = parseMatchId(params.matchId);
  const relationshipTypeParam = parseRelationshipType(params.relationshipType);
  const relationLabelParam = Array.isArray(params.relationLabel) ? params.relationLabel[0] : params.relationLabel;
  const overallScore = Number.isFinite(Number(params.overallScore)) ? Number(params.overallScore) : null;

  const { data, loading, error, isMock, refetch } = useMatchTraits(matchId, {
    personAName: params.personAName,
    personBName: params.personBName,
    personASignLabel: params.personASignLabel,
    personBSignLabel: params.personBSignLabel,
    overallScore,
  });

  const [meta, setMeta] = useState<SynastryCardMeta>({
    relationshipType: relationshipTypeParam,
    relationLabel: relationLabelParam ?? null,
    scoreBreakdown: null,
    displayMetrics: null,
  });

  const viewShotRef = useRef<ViewShot | null>(null);
  const [layoutTick, setLayoutTick] = useState(0);
  const [actionLoading, setActionLoading] = useState<ShareAction>(null);
  const [successText, setSuccessText] = useState<string | null>(null);
  const { imageUri, loading: imageLoading, error: imageError, generate, retry } = useGenerateMatchImage(viewShotRef, {
    width: 1080,
    height: 2160,
    cacheSubdir: 'share-card-preview',
    filePrefix: 'synastry-card',
  });
  const autoGeneratedForKeyRef = useRef<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const hydrateFromSynastry = async () => {
      if (!matchId) return;
      try {
        const response = await getSynastry(matchId);
        if (cancelled) return;

        const syn = response.data;
        const synType = parseRelationshipType(syn.relationshipType as any);
        const resolvedType = relationshipTypeParam ?? synType ?? null;
        setMeta({
          relationshipType: resolvedType,
          relationLabel: relationLabelParam ?? null,
          scoreBreakdown: syn.scoreBreakdown
            ? {
                overall: syn.scoreBreakdown.overall ?? null,
                love: syn.scoreBreakdown.love ?? null,
                communication: syn.scoreBreakdown.communication ?? null,
                spiritualBond: syn.scoreBreakdown.spiritualBond ?? null,
              }
            : null,
          displayMetrics: syn.displayMetrics ?? null,
        });
      } catch {
        if (cancelled) return;
        setMeta((prev) => ({
          ...prev,
          relationshipType: relationshipTypeParam ?? prev.relationshipType ?? null,
          relationLabel: prev.relationLabel ?? relationLabelParam ?? null,
        }));
      }
    };

    void hydrateFromSynastry();

    return () => {
      cancelled = true;
    };
  }, [matchId, relationLabelParam, relationshipTypeParam]);

  const preview = useMemo(() => {
    if (!data) return null;

    const leftName =
      data.people.left.name ||
      (Array.isArray(params.personAName) ? params.personAName[0] : params.personAName) ||
      'Kişi A';
    const rightName =
      data.people.right.name ||
      (Array.isArray(params.personBName) ? params.personBName[0] : params.personBName) ||
      'Kişi B';
    const leftSign =
      (Array.isArray(params.personASignLabel) ? params.personASignLabel[0] : params.personASignLabel) ||
      data.people.left.signLabel;
    const rightSign =
      (Array.isArray(params.personBSignLabel) ? params.personBSignLabel[0] : params.personBSignLabel) ||
      data.people.right.signLabel;

    return {
      user1Name: leftName,
      user2Name: rightName,
      user1Sign: leftSign,
      user2Sign: rightSign,
      compatibilityScore: data.overallScore,
      relationshipType: relationshipTypeParam ?? meta.relationshipType ?? undefined,
      relationLabel: meta.relationLabel ?? relationLabelParam ?? undefined,
      aiSummary: data.summaryPlain.body,
      cardSummary: data.summaryPlain.body,
      aspectsCount: data.aspectsEvaluated,
      traitAxes: toTraitAxes(data.axes),
      scoreBreakdown: meta.scoreBreakdown,
      displayMetrics: meta.displayMetrics,
    };
  }, [
    data,
    meta.displayMetrics,
    meta.relationLabel,
    meta.relationshipType,
    params.personAName,
    params.personASignLabel,
    params.personBName,
    params.personBSignLabel,
    relationLabelParam,
    relationshipTypeParam,
  ]);

  const previewKey = useMemo(() => {
    if (!preview) return null;
    return [
      preview.user1Name,
      preview.user2Name,
      preview.compatibilityScore,
      preview.relationshipType ?? 'na',
      preview.aspectsCount,
    ].join('|');
  }, [preview]);

  useEffect(() => {
    autoGeneratedForKeyRef.current = null;
    setSuccessText(null);
  }, [previewKey]);

  useEffect(() => {
    if (!preview || !layoutTick) return;
    if (autoGeneratedForKeyRef.current === previewKey) return;
    autoGeneratedForKeyRef.current = previewKey;
    void generate().catch(() => {
      // Hook error state handled by useGenerateMatchImage.
    });
  }, [generate, layoutTick, preview, previewKey]);

  useEffect(() => {
    if (!successText) return;
    const timer = setTimeout(() => setSuccessText(null), 1800);
    return () => clearTimeout(timer);
  }, [successText]);

  const notifySuccess = async (message: string) => {
    setSuccessText(message);
    try {
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch {
      // no-op
    }
  };

  const presentShareError = useCallback(async (title: string, cause: unknown) => {
    const errorObj =
      cause instanceof ShareServiceError
        ? cause
        : new Error((cause as any)?.message ?? 'İşlem tamamlanamadı.');

    const openSettings = async () => {
      try {
        await Linking.openSettings();
      } catch {
        Alert.alert('Ayarlar açılamadı', 'Lütfen Ayarlar uygulamasını manuel olarak açın.');
      }
    };

    if (errorObj instanceof ShareServiceError && errorObj.suggestOpenSettings) {
      Alert.alert(title, errorObj.message, [
        { text: 'Vazgeç', style: 'cancel' },
        { text: 'Ayarları Aç', onPress: () => void openSettings() },
      ]);
      return;
    }

    Alert.alert(title, errorObj.message);
  }, []);

  const runShareAction = async (
    action: Exclude<ShareAction, null>,
    errorTitle: string,
    fn: () => Promise<void>,
  ) => {
    if (!imageUri) return;
    setActionLoading(action);
    try {
      await fn();
    } catch (e: any) {
      await presentShareError(errorTitle, e);
    } finally {
      setActionLoading(null);
    }
  };

  const handleShare = async () => {
    await runShareAction('share', 'Paylaşım Hatası', async () => {
      await shareImage(imageUri!);
      await notifySuccess('Paylaşım menüsü açıldı');
    });
  };

  const handleSave = async () => {
    await runShareAction('save', 'Kaydetme Hatası', async () => {
      const result = await saveToGallery(imageUri!);
      await notifySuccess(result.message ?? 'Görsel galeriye kaydedildi');
    });
  };

  const handleRegenerate = async () => {
    setActionLoading('regenerate');
    setSuccessText(null);
    try {
      await retry();
      await notifySuccess('Kart güncellendi');
    } catch (e) {
      await presentShareError('Kart Oluşturulamadı', e);
    } finally {
      setActionLoading(null);
    }
  };

  const shareDisabled = !imageUri || imageLoading || !!actionLoading;

  return (
    <SafeScreen edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.bg }}>
      <View pointerEvents="none" style={styles.captureHost}>
        <ViewShot
          ref={viewShotRef}
          style={styles.captureCanvas}
          onLayout={() => setLayoutTick(Date.now())}
          options={{
            format: 'png',
            quality: 1,
            result: 'tmpfile',
            width: 1080,
            height: 2160,
          } as any}
        >
          {preview ? (
            <MatchCard
              user1Name={preview.user1Name}
              user2Name={preview.user2Name}
              user1Sign={preview.user1Sign}
              user2Sign={preview.user2Sign}
              compatibilityScore={preview.compatibilityScore}
              relationshipType={preview.relationshipType}
              relationLabel={preview.relationLabel}
              aiSummary={preview.aiSummary}
              cardSummary={preview.cardSummary}
              traitAxes={preview.traitAxes}
              aspectsCount={preview.aspectsCount}
              scoreBreakdown={preview.scoreBreakdown}
              displayMetrics={preview.displayMetrics}
            />
          ) : (
            <View style={styles.capturePlaceholder} />
          )}
        </ViewShot>
      </View>

      <View style={styles.container}>
        <AppHeader title="Paylaşılabilir Kart" subtitle="Güncel synastry kartı ve profesyonel paylaşım atölyesi" />

        {isMock || error ? (
          <View style={[styles.banner, { backgroundColor: colors.violetBg, borderColor: colors.violetLight }]}> 
            <Ionicons name="information-circle-outline" size={14} color={colors.violet} />
            <AccessibleText style={[styles.bannerText, { color: colors.violet }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
              {isMock ? 'Kart örnek veriyle gösteriliyor.' : `Canlı veri sorunu: ${error}`}
            </AccessibleText>
          </View>
        ) : null}

        {imageError ? (
          <View style={[styles.banner, { backgroundColor: '#FEF2F2', borderColor: '#FECACA' }]}> 
            <Ionicons name="alert-circle-outline" size={14} color="#B91C1C" />
            <AccessibleText style={[styles.bannerText, { color: '#B91C1C' }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
              {imageError}
            </AccessibleText>
          </View>
        ) : null}

        {successText ? (
          <View style={[styles.banner, { backgroundColor: colors.successBg, borderColor: colors.successLight }]}> 
            <Ionicons name="checkmark-circle" size={14} color={colors.success} />
            <AccessibleText style={[styles.bannerText, { color: colors.success }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
              {successText}
            </AccessibleText>
          </View>
        ) : null}

        <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
          {loading && !preview ? (
            <View style={[styles.stateCard, { backgroundColor: colors.surface, borderColor: colors.border }]}> 
              <ActivityIndicator size="small" color={colors.violet} />
              <AccessibleText style={[styles.stateText, { color: colors.subtext }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                Kart hazırlanıyor…
              </AccessibleText>
            </View>
          ) : null}

          {!loading && !preview ? (
            <View style={[styles.stateCard, { backgroundColor: colors.surface, borderColor: colors.border }]}> 
              <AccessibleText style={[styles.stateText, { color: colors.subtext }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                Kart içeriği alınamadı.
              </AccessibleText>
              <Pressable
                onPress={() => {
                  void refetch();
                }}
                style={[styles.retryBtn, { backgroundColor: colors.surfaceAlt, borderColor: colors.border }]}
              >
                <AccessibleText style={[styles.retryText, { color: colors.text }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                  Tekrar dene
                </AccessibleText>
              </Pressable>
            </View>
          ) : null}

          {preview ? (
            <View style={styles.previewWrap}>
              <MatchCard
                user1Name={preview.user1Name}
                user2Name={preview.user2Name}
                user1Sign={preview.user1Sign}
                user2Sign={preview.user2Sign}
                compatibilityScore={preview.compatibilityScore}
                relationshipType={preview.relationshipType}
                relationLabel={preview.relationLabel}
                aiSummary={preview.aiSummary}
                cardSummary={preview.cardSummary}
                traitAxes={preview.traitAxes}
                aspectsCount={preview.aspectsCount}
                scoreBreakdown={preview.scoreBreakdown}
                displayMetrics={preview.displayMetrics}
              />
            </View>
          ) : null}

          {preview ? (
            <View style={[styles.actionCard, { backgroundColor: colors.surface, borderColor: colors.border }]}> 
              <View style={styles.actionHeader}>
                <Ionicons name="share-social-outline" size={16} color={colors.violet} />
                <AccessibleText style={[styles.actionTitle, { color: colors.text }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                  Paylaşım Atölyesi
                </AccessibleText>
              </View>
              <AccessibleText style={[styles.actionSub, { color: colors.subtext }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                Hemen Paylaş ile cihazındaki uygulamalar (Instagram dahil) üzerinden paylaş.
              </AccessibleText>

              <View style={styles.quickActionsGrid}>
                <Pressable
                  style={[
                    styles.quickActionItem,
                    styles.quickActionWide,
                    styles.quickActionPrimary,
                    { backgroundColor: colors.violet, borderColor: colors.violet },
                    shareDisabled && styles.btnDisabled,
                  ]}
                  onPress={() => void handleShare()}
                  disabled={shareDisabled}
                >
                  {actionLoading === 'share' ? (
                    <ActivityIndicator size="small" color="#FFFFFF" />
                  ) : (
                    <Ionicons name="share-social-outline" size={24} color="#FFFFFF" />
                  )}
                  <AccessibleText style={styles.quickActionPrimaryText} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                    Hemen Paylaş
                  </AccessibleText>
                </Pressable>

                <Pressable
                  style={[
                    styles.quickActionItem,
                    { borderColor: colors.border, backgroundColor: colors.surfaceAlt },
                    shareDisabled && styles.btnDisabled,
                  ]}
                  onPress={() => void handleSave()}
                  disabled={shareDisabled}
                >
                  {actionLoading === 'save' ? (
                    <ActivityIndicator size="small" color={colors.violet} />
                  ) : (
                    <Ionicons name="download-outline" size={24} color={colors.violet} />
                  )}
                  <AccessibleText style={[styles.quickActionText, { color: colors.text }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                    Kaydet
                  </AccessibleText>
                </Pressable>

                <Pressable
                  style={[
                    styles.quickActionItem,
                    { borderColor: colors.border, backgroundColor: colors.surfaceAlt },
                    (!!actionLoading || imageLoading) && styles.btnDisabled,
                  ]}
                  onPress={() => void handleRegenerate()}
                  disabled={!!actionLoading || imageLoading}
                >
                  {actionLoading === 'regenerate' || imageLoading ? (
                    <ActivityIndicator size="small" color={colors.muted} />
                  ) : (
                    <Ionicons name="refresh-outline" size={24} color={colors.muted} />
                  )}
                  <AccessibleText style={[styles.quickActionText, { color: colors.subtext }]} maxFontSizeMultiplier={ACCESSIBILITY.maxFontSizeMultiplier}>
                    Yenile
                  </AccessibleText>
                </Pressable>
              </View>
            </View>
          ) : null}
        </ScrollView>
      </View>
    </SafeScreen>
  );
}

const styles = StyleSheet.create({
  captureHost: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
    left: -9999,
    top: -9999,
  },
  captureCanvas: {
    width: 360,
    height: 720,
  },
  capturePlaceholder: {
    width: 360,
    height: 720,
    backgroundColor: '#F5E8FF',
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    gap: 12,
  },
  banner: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  bannerText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  scroll: {
    paddingBottom: 24,
    gap: 12,
  },
  previewWrap: {
    alignItems: 'center',
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.13,
    shadowRadius: 18,
    elevation: 6,
  },
  stateCard: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    alignItems: 'center',
    gap: 8,
  },
  stateText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
  },
  retryBtn: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    fontSize: 13,
    fontWeight: '700',
  },
  actionCard: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  actionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
  },
  actionSub: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickActionItem: {
    width: '48.5%',
    minHeight: 82,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  quickActionWide: {
    width: '100%',
    minHeight: 78,
  },
  quickActionPrimary: {
    shadowColor: '#7C3AED',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 3,
  },
  quickActionPrimaryText: {
    color: '#FFFFFF',
    fontSize: 11.8,
    lineHeight: 14.5,
    fontWeight: '800',
    textAlign: 'center',
  },
  quickActionText: {
    fontSize: 11.5,
    lineHeight: 14.5,
    fontWeight: '700',
    textAlign: 'center',
  },
  btnDisabled: {
    opacity: 0.58,
  },
});
